export const cities = [
  `Achalpur`,
  `Achhnera`,
  `Adalaj`,
  `Adilabad`,
  `Adityapur`,
  `Adoni`,
  `Adoor`,
  `Adra`,
  `Adyar`,
  `Afzalpur`,
  `Agartala`,
  `Agra`,
  `Ahmedabad`,
  `Ahmednagar`,
  `Aizawl`,
  `Ajitgarh (Mohali)`,
  `Ajmer`,
  `Akola`,
  `Akot`,
  `Alappuzha`,
  `Aligarh`,
  `AlipurdUrban Agglomerationr`,
  `Alirajpur`,
  `Allahabad`,
  `Almora`,
  `Alwar`,
  `Amalapuram`,
  `Amalner`,
  `Ambala`,
  `Ambedkar Nagar`,
  `Ambejogai`,
  `Ambikapur`,
  `Amravati`,
  `Amreli`,
  `Amreli district`,
  `Amritsar`,
  `Amroha`,
  `Anakapalle`,
  `Anand`,
  `Anantapur`,
  `Anantnag`,
  `Angul`,
  `Anjangaon`,
  `Anjar`,
  `Anjaw`,
  `Ankleshwar`,
  `Anuppur`,
  `Arakkonam`,
  `Arambagh`,
  `Araria`,
  `Ariyalur`,
  `Arrah`,
  `Arsikere`,
  `Aruppukkottai`,
  `Arvi`,
  `Arwal`,
  `Asansol`,
  `Asarganj`,
  `Ashok Nagar`,
  `Athni`,
  `Attingal`,
  `Auraiya`,
  `Aurangabad`,
  `Azamgarh`,
  `Badgam`,
  `Bagaha`,
  `Bagalkot`,
  `Bageshwar`,
  `Bagpat`,
  `Bahadurgarh`,
  `Baharampur`,
  `Bahraich`,
  `Baksa`,
  `Balaghat`,
  `Balangir`,
  `Balasore`,
  `Baleshwar Town`,
  `Ballari`,
  `Ballia`,
  `Balrampur`,
  `Balurghat`,
  `Banaskantha`,
  `Banda`,
  `Bandipora`,
  `Bangalore Rural`,
  `Bangalore Urban`,
  `Banka`,
  `Bankura`,
  `Banswara`,
  `Bapatla`,
  `Barabanki`,
  `Baramula`,
  `Baramulla`,
  `Baran`,
  `Barbil`,
  `Bardhaman`,
  `Bareilly`,
  `Bargarh`,
  `Bargarh (Baragarh)`,
  `Barh`,
  `Baripada Town`,
  `Barmer`,
  `Barnala`,
  `Barpeta`,
  `Barwani`,
  `Bastar`,
  `Basti`,
  `Batala`,
  `Bathinda`,
  `Beed`,
  `Begusarai`,
  `Belagavi`,
  `Belgaum`,
  `Bellampalle`,
  `Bellary`,
  `Belonia`,
  `Bengaluru`,
  `Bettiah`,
  `Betul`,
  `BhabUrban Agglomeration`,
  `Bhadrachalam`,
  `Bhadrak`,
  `Bhagalpur`,
  `Bhainsa`,
  `Bhandara`,
  `Bharatpur`,
  `Bharuch`,
  `Bhatapara`,
  `Bhavnagar`,
  `Bhawanipatna`,
  `Bheemunipatnam`,
  `Bhilai Nagar`,
  `Bhilwara`,
  `Bhimavaram`,
  `Bhind`,
  `Bhiwandi`,
  `Bhiwani`,
  `Bhojpur`,
  `Bhongir`,
  `Bhopal`,
  `Bhubaneswar`,
  `Bhuj`,
  `Bidar`,
  `Bijapur`,
  `Bijnor`,
  `Bikaner`,
  `Bilaspur`,
  `Birbhum`,
  `Bishnupur`,
  `Bobbili`,
  `Bodhan`,
  `Bokaro`,
  `Bokaro Steel City`,
  `Bongaigaon`,
  `Bongaigaon City`,
  `Boudh (Bauda)`,
  `Brahmapur`,
  `Budaun`,
  `Bulandshahr`,
  `Buldhana`,
  `Bundi`,
  `Burhanpur`,
  `Buxar`,
  `Byasanagar`,
  `Cachar`,
  `Central Delhi`,
  `Chaibasa`,
  `Chalakudy`,
  `Chamarajnagar`,
  `Chamba`,
  `Chamoli`,
  `Champawat`,
  `Champhai`,
  `Chandauli`,
  `Chandausi`,
  `Chandel`,
  `Chandigarh`,
  `Chandrapur`,
  `Changanassery`,
  `Changlang`,
  `Charkhi Dadri`,
  `Chatra`,
  `Chennai`,
  `Cherthala`,
  `Chhapra`,
  `Chhatarpur`,
  `Chhatrapati Shahuji Maharaj Nagar`,
  `Chhindwara`,
  `Chikkaballapur`,
  `Chikkamagaluru`,
  `Chilakaluripet`,
  `Chirala`,
  `Chirang`,
  `Chirkunda`,
  `Chirmiri`,
  `Chitradurga`,
  `Chitrakoot`,
  `Chittoor`,
  `Chittorgarh`,
  `Chittur-Thathamangalam`,
  `Churachandpur`,
  `Churu`,
  `Coimbatore`,
  `Cooch Behar`,
  `Cuddalore`,
  `Cuttack`,
  `Dadra and Nagar Haveli`,
  `Dahod`,
  `Dakshin Dinajpur`,
  `Dakshina Kannada`,
  `Dalli-Rajhara`,
  `Daman`,
  `Damoh`,
  `Dantewada`,
  `Darbhanga`,
  `Darjeeling`,
  `Darjiling`,
  `Darrang`,
  `Datia`,
  `Dausa`,
  `Davanagere`,
  `Debagarh (Deogarh)`,
  `Deesa`,
  `Dehradun`,
  `Dehri-on-Sone`,
  `Delhi`,
  `Deoghar`,
  `Deoria`,
  `Dewas`,
  `Dhalai`,
  `Dhamtari`,
  `Dhanbad`,
  `Dhar`,
  `Dharmanagar`,
  `Dharmapuri`,
  `Dharmavaram`,
  `Dharwad`,
  `Dhemaji`,
  `Dhenkanal`,
  `Dholpur`,
  `Dhoraji`,
  `Dhubri`,
  `Dhule`,
  `Dhuri`,
  `Dibang Valley`,
  `Dibrugarh`,
  `Dima Hasao`,
  `Dimapur`,
  `Dindigul`,
  `Dindori`,
  `Diphu`,
  `Diu`,
  `Doda`,
  `Dumka`,
  `Dumraon`,
  `Dungapur`,
  `Durg`,
  `East Champaran`,
  `East Delhi`,
  `East Garo Hills`,
  `East Khasi Hills`,
  `East Siang`,
  `East Sikkim`,
  `East Singhbhum`,
  `Eluru`,
  `English Bazar`,
  `Ernakulam`,
  `Erode`,
  `Etah`,
  `Etawah`,
  `Faizabad`,
  `Faridabad`,
  `Faridkot`,
  `Farooqnagar`,
  `Farrukhabad`,
  `Fatehabad`,
  `Fatehgarh Sahib`,
  `Fatehpur`,
  `Fatehpur Sikri`,
  `Fazilka`,
  `Firozabad`,
  `Firozpur`,
  `Firozpur Cantt.`,
  `Forbesganj`,
  `Gadag`,
  `Gadchiroli`,
  `Gadwal`,
  `Gajapati`,
  `Ganderbal`,
  `Gandhinagar`,
  `Ganganagar`,
  `Gangarampur`,
  `Ganjam`,
  `Ganjbasoda`,
  `Garhwa`,
  `Gautam Buddh Nagar`,
  `Gaya`,
  `Ghaziabad`,
  `Ghazipur`,
  `Giridih`,
  `Goalpara`,
  `Gobichettipalayam`,
  `Gobindgarh`,
  `Godda`,
  `Godhra`,
  `Gohana`,
  `Gokak`,
  `Golaghat`,
  `Gonda`,
  `Gondia`,
  `Gooty`,
  `Gopalganj`,
  `Gorakhpur`,
  `Gudivada`,
  `Gudur`,
  `Gulbarga`,
  `Gumia`,
  `Gumla`,
  `Guna`,
  `Guntakal`,
  `Guntur`,
  `Gurdaspur`,
  `Gurgaon`,
  `Guruvayoor`,
  `Guwahati`,
  `Gwalior`,
  `Habra`,
  `Hailakandi`,
  `Hajipur`,
  `Haldwani-*****-Kathgodam`,
  `Hamirpur`,
  `Hansi`,
  `Hanumangarh`,
  `Hapur`,
  `Harda`,
  `Hardoi`,
  `Hardoi `,
  `Hardwar`,
  `Haridwar`,
  `Hassan`,
  `Haveri district`,
  `Hazaribag`,
  `Hindupur`,
  `Hingoli`,
  `Hisar`,
  `Hissar`,
  `Hooghly`,
  `Hoshangabad`,
  `Hoshiarpur`,
  `Howrah`,
  `Hubli-Dharwad`,
  `Hugli-Chinsurah`,
  `Hyderabad`,
  `Ichalkaranji`,
  `Idukki`,
  `Imphal`,
  `Imphal East`,
  `Imphal West`,
  `Indore`,
  `Itarsi`,
  `Jabalpur`,
  `Jagatsinghpur`,
  `Jagdalpur`,
  `Jaggaiahpet`,
  `Jagraon`,
  `Jagtial`,
  `Jaintia Hills`,
  `Jaipur`,
  `Jaisalmer`,
  `Jajpur`,
  `Jalandhar`,
  `Jalandhar Cantt.`,
  `Jalaun`,
  `Jalgaon`,
  `Jalna`,
  `Jalore`,
  `Jalpaiguri`,
  `Jamalpur`,
  `Jammalamadugu`,
  `Jammu`,
  `Jamnagar`,
  `Jamshedpur`,
  `Jamtara`,
  `Jamui`,
  `Jangaon`,
  `Janjgir-Champa`,
  `Jashpur`,
  `Jatani`,
  `Jaunpur district`,
  `Jehanabad`,
  `Jhabua`,
  `Jhajjar`,
  `Jhalawar`,
  `Jhansi`,
  `Jhargram`,
  `Jharsuguda`,
  `Jhumri Tilaiya`,
  `Jhunjhunu`,
  `Jind`,
  `Jodhpur`,
  `Jorhat`,
  `Junagadh`,
  `Jyotiba Phule Nagar`,
  `Kabirdham (formerly Kawardha)`,
  `Kadapa`,
  `Kadi`,
  `Kadiri`,
  `Kagaznagar`,
  `Kailasahar`,
  `Kaimur`,
  `Kaithal`,
  `Kakinada`,
  `Kalahandi`,
  `Kalimpong`,
  `Kalpi`,
  `Kalyan-Dombivali`,
  `Kamareddy`,
  `Kamrup`,
  `Kamrup Metropolitan`,
  `Kancheepuram`,
  `Kanchipuram`,
  `Kandhamal`,
  `Kandukur`,
  `Kangra`,
  `Kanhangad`,
  `Kanker`,
  `Kannauj`,
  `Kannur`,
  `Kanpur`,
  `Kanshi Ram Nagar`,
  `Kanyakumari`,
  `Kapadvanj`,
  `Kapurthala`,
  `Karaikal`,
  `Karauli`,
  `Karbi Anglong`,
  `Kargil`,
  `Karimganj`,
  `Karimnagar`,
  `Karjat`,
  `Karnal`,
  `Karur`,
  `Karwar`,
  `Kasaragod`,
  `Kashipur`,
  `KathUrban Agglomeration`,
  `Kathua`,
  `Katihar`,
  `Katni`,
  `Kaushambi`,
  `Kavali`,
  `Kayamkulam`,
  `Kendrapara`,
  `Kendujhar`,
  `Kendujhar (Keonjhar)`,
  `Keshod`,
  `Khagaria`,
  `Khair`,
  `Khambhat`,
  `Khammam`,
  `Khandwa (East Nimar)`,
  `Khanna`,
  `Kharagpur`,
  `Kharar`,
  `Khargone (West Nimar)`,
  `Kheda`,
  `Khordha`,
  `Khowai`,
  `Khunti`,
  `Kinnaur`,
  `Kishanganj`,
  `Kishtwar`,
  `Kochi`,
  `Kodagu`,
  `Koderma`,
  `Kodungallur`,
  `Kohima`,
  `Kokrajhar`,
  `Kolar`,
  `Kolasib`,
  `Kolhapur`,
  `Kolkata`,
  `Kollam`,
  `Koppal`,
  `Koraput`,
  `Koratla`,
  `Korba`,
  `Koriya`,
  `Kot Kapura`,
  `Kota`,
  `Kothagudem`,
  `Kottayam`,
  `Kovvur`,
  `Koyilandy`,
  `Kozhikode`,
  `Krishna`,
  `Kulgam`,
  `Kullu`,
  `Kunnamkulam`,
  `Kupwara`,
  `Kurnool`,
  `Kurukshetra`,
  `Kurung Kumey`,
  `Kushinagar`,
  `Kutch`,
  `Kyathampalle`,
  `Lachhmangarh`,
  `Ladnu`,
  `Ladwa`,
  `Lahar`,
  `Laharpur`,
  `Lahaul and Spiti`,
  `Lakheri`,
  `Lakhimpur`,
  `Lakhimpur Kheri`,
  `Lakhisarai`,
  `Lakshmeshwar`,
  `Lal Gopalganj Nindaura`,
  `Lalganj`,
  `Lalgudi`,
  `Lalitpur`,
  `Lalsot`,
  `Lanka`,
  `Lar`,
  `Latehar`,
  `Lathi`,
  `Latur`,
  `Lawngtlai`,
  `Leh`,
  `Lilong`,
  `Limbdi`,
  `Lingsugur`,
  `Loha`,
  `Lohardaga`,
  `Lohit`,
  `Lonar`,
  `Lonavla`,
  `Longowal`,
  `Loni`,
  `Losal`,
  `Lower Dibang Valley`,
  `Lower Subansiri`,
  `Lucknow`,
  `Ludhiana`,
  `Lumding`,
  `Lunawada`,
  `Lunglei`,
  `Macherla`,
  `Machilipatnam`,
  `Madanapalle`,
  `Maddur`,
  `Madhepura`,
  `Madhubani`,
  `Madhugiri`,
  `Madhupur`,
  `Madikeri`,
  `Madurai`,
  `Magadi`,
  `Mahad`,
  `Mahalingapura`,
  `Mahamaya Nagar`,
  `Maharajganj`,
  `Maharajpur`,
  `Mahasamund`,
  `Mahbubnagar`,
  `Mahe`,
  `Mahemdabad`,
  `Mahendragarh`,
  `Mahesana`,
  `Mahidpur`,
  `Mahnar Bazar`,
  `Mahoba`,
  `Mahuva`,
  `Maihar`,
  `Mainaguri`,
  `Mainpuri`,
  `Makhdumpur`,
  `Makrana`,
  `Malaj Khand`,
  `Malappuram`,
  `Malavalli`,
  `Malda`,
  `Maldah`,
  `Malegaon`,
  `Malerkotla`,
  `Malkangiri`,
  `Malkapur`,
  `Malout`,
  `Malpura`,
  `Malur`,
  `Mamit`,
  `Manachanallur`,
  `Manasa`,
  `Manavadar`,
  `Manawar`,
  `Mancherial`,
  `Mandalgarh`,
  `Mandamarri`,
  `Mandapeta`,
  `Mandawa`,
  `Mandi`,
  `Mandi Dabwali`,
  `Mandideep`,
  `Mandla`,
  `Mandsaur`,
  `Mandvi`,
  `Mandya`,
  `Manendragarh`,
  `Maner`,
  `Mangaldoi`,
  `Mangaluru`,
  `Mangalvedhe`,
  `Manglaur`,
  `Mangrol`,
  `Mangrulpir`,
  `Manihari`,
  `Manjlegaon`,
  `Mankachar`,
  `Manmad`,
  `Mansa`,
  `Manuguru`,
  `Manvi`,
  `Manwath`,
  `Mapusa`,
  `Margao`,
  `Margherita`,
  `Marhaura`,
  `Mariani`,
  `Marigaon`,
  `Markapur`,
  `Marmagao`,
  `Masaurhi`,
  `Mathabhanga`,
  `Mathura`,
  `Mattannur`,
  `Mau`,
  `Mauganj`,
  `Mavelikkara`,
  `Mavoor`,
  `Mayang Imphal`,
  `Mayurbhanj`,
  `Medak`,
  `Medininagar (Daltonganj)`,
  `Medinipur`,
  `Meerut`,
  `Mehkar`,
  `Mehsana`,
  `Memari`,
  `Merta City`,
  `Mewat`,
  `Mhaswad`,
  `Mhow Cantonment`,
  `Mhowgaon`,
  `Mihijam`,
  `Mira-Bhayandar`,
  `Mirganj`,
  `Miryalaguda`,
  `Mirzapur`,
  `Modasa`,
  `Modinagar`,
  `Moga`,
  `Mohali`,
  `Mokameh`,
  `Mokokchung`,
  `Mon`,
  `Monoharpur`,
  `Moradabad`,
  `Morena`,
  `Morinda, India`,
  `Morshi`,
  `Morvi`,
  `Motihari`,
  `Motipur`,
  `Mount Abu`,
  `Mudabidri`,
  `Mudalagi`,
  `Muddebihal`,
  `Mudhol`,
  `Mukerian`,
  `Mukhed`,
  `Muktsar`,
  `Mul`,
  `Mulbagal`,
  `Multai`,
  `Mumbai`,
  `Mumbai City`,
  `Mumbai suburban`,
  `Mundargi`,
  `Mundi`,
  `Mungeli`,
  `Munger`,
  `Murliganj`,
  `Murshidabad`,
  `Murtijapur`,
  `Murwara (Katni)`,
  `Musabani`,
  `Mussoorie`,
  `Muvattupuzha`,
  `Muzaffarnagar`,
  `Muzaffarpur`,
  `Mysore`,
  `Nabadwip`,
  `Nabarangapur`,
  `Nabarangpur`,
  `Nabha`,
  `Nadbai`,
  `Nadia`,
  `Nadiad`,
  `Nagaon`,
  `Nagapattinam`,
  `Nagar`,
  `Nagari`,
  `Nagarkurnool`,
  `Nagaur`,
  `Nagda`,
  `Nagercoil`,
  `Nagina`,
  `Nagla`,
  `Nagpur`,
  `Nahan`,
  `Naharlagun`,
  `Naidupet`,
  `Naihati`,
  `Naila Janjgir`,
  `Nainital`,
  `Nainpur`,
  `Najibabad`,
  `Nakodar`,
  `Nakur`,
  `Nalanda`,
  `Nalbari`,
  `Nalgonda`,
  `Namagiripettai`,
  `Namakkal`,
  `Nanded`,
  `Nanded-Waghala`,
  `Nandgaon`,
  `Nandivaram-Guduvancheri`,
  `Nandura`,
  `Nandurbar`,
  `Nandyal`,
  `Nangal`,
  `Nanjangud`,
  `Nanjikottai`,
  `Nanpara`,
  `Narasapuram`,
  `Narasaraopet`,
  `Naraura`,
  `Narayanpet`,
  `Narayanpur`,
  `Nargund`,
  `Narkatiaganj`,
  `Narkhed`,
  `Narmada`,
  `Narnaul`,
  `Narsinghgarh`,
  `Narsinghpur`,
  `Narsipatnam`,
  `Narwana`,
  `Nashik`,
  `Nasirabad`,
  `Natham`,
  `Nathdwara`,
  `Naugachhia`,
  `Naugawan Sadat`,
  `Nautanwa`,
  `Navalgund`,
  `Navsari`,
  `Nawabganj`,
  `Nawada`,
  `Nawanshahr`,
  `Nawapur`,
  `Nayagarh`,
  `Nedumangad`,
  `Neem-Ka-Thana`,
  `Neemuch`,
  `Nehtaur`,
  `Nelamangala`,
  `Nellikuppam`,
  `Nellore`,
  `Nepanagar`,
  `New Delhi`,
  `Neyveli (TS)`,
  `Neyyattinkara`,
  `Nidadavole`,
  `Nilambur`,
  `Nilanga`,
  `Nilgiris`,
  `Nimbahera`,
  `Nirmal`,
  `Niwai`,
  `Niwari`,
  `Nizamabad`,
  `Nohar`,
  `Noida`,
  `Nokha`,
  `Nongstoin`,
  `Noorpur`,
  `North 24 Parganas`,
  `North Delhi`,
  `North East Delhi`,
  `North Goa`,
  `North Lakhimpur`,
  `North Sikkim`,
  `North Tripura`,
  `North West Delhi`,
  `Nowgong`,
  `Nowrozabad (Khodargama)`,
  `Nuapada`,
  `Nuzvid`,
  `O' Valley`,
  `Obra`,
  `Oddanchatram`,
  `Ongole`,
  `Orai`,
  `Osmanabad`,
  `Other`,
  `Ottappalam`,
  `Ozar`,
  `P.N.Patti`,
  `Pachora`,
  `Pachore`,
  `Pacode`,
  `Padmanabhapuram`,
  `Padra`,
  `Padrauna`,
  `Paithan`,
  `Pakaur`,
  `Pakur`,
  `Palacole`,
  `Palai`,
  `Palakkad`,
  `Palampur`,
  `Palamu`,
  `Palani`,
  `Palanpur`,
  `Palasa Kasibugga`,
  `Palghar`,
  `Pali`,
  `Palia Kalan`,
  `Palitana`,
  `Palladam`,
  `Pallapatti`,
  `Pallikonda`,
  `Palwal`,
  `Palwancha`,
  `Panagar`,
  `Panagudi`,
  `Panaji`,
  `Panamattom`,
  `Panchkula`,
  `Panchla`,
  `Panchmahal`,
  `Panchsheel Nagar district (Hapur)`,
  `PandUrban Agglomeration`,
  `Pandharkaoda`,
  `Pandharpur`,
  `Pandhurna`,
  `Panipat`,
  `Panna`,
  `Panniyannur`,
  `Panruti`,
  `Panvel`,
  `Pappinisseri`,
  `Papum Pare`,
  `Paradip`,
  `Paramakudi`,
  `Parangipettai`,
  `Parasi`,
  `Paravoor`,
  `Parbhani`,
  `Pardi`,
  `Parlakhemundi`,
  `Parli`,
  `Partur`,
  `Parvathipuram`,
  `Pasan`,
  `Paschim Medinipur`,
  `Paschim Punropara`,
  `Pasighat`,
  `Patan`,
  `Pathanamthitta`,
  `Pathankot`,
  `Pathardi`,
  `Pathri`,
  `Patiala`,
  `Patna`,
  `Patratu`,
  `Pattamundai`,
  `Patti`,
  `Pattran`,
  `Pattukkottai`,
  `Patur`,
  `Pauni`,
  `Pauri`,
  `Pauri Garhwal`,
  `Pavagada`,
  `Pedana`,
  `Peddapuram`,
  `Pehowa`,
  `Pen`,
  `Perambalur`,
  `Peravurani`,
  `Peringathur`,
  `Perinthalmanna`,
  `Periyakulam`,
  `Periyasemur`,
  `Pernampattu`,
  `Perumbavoor`,
  `Petlad`,
  `Phagwara`,
  `Phalodi`,
  `Phaltan`,
  `Phek`,
  `Phillaur`,
  `Phulabani`,
  `Phulera`,
  `Phulpur`,
  `Phusro`,
  `Pihani`,
  `Pilani`,
  `Pilibanga`,
  `Pilibhit`,
  `Pilkhuwa`,
  `Pindwara`,
  `Pinjore`,
  `Pipar City`,
  `Pipariya`,
  `Piriyapatna`,
  `Piro`,
  `Pithampur`,
  `Pithapuram`,
  `Pithoragarh`,
  `Pollachi`,
  `Polur`,
  `Pondicherry`,
  `Ponnani`,
  `Ponneri`,
  `Ponnur`,
  `Poonch`,
  `Porbandar`,
  `Porsa`,
  `Port Blair`,
  `Powayan`,
  `Prantij`,
  `Pratapgarh`,
  `Prithvipur`,
  `Proddatur`,
  `Pudukkottai`,
  `Pudupattinam`,
  `Pukhrayan`,
  `Pulgaon`,
  `Puliyankudi`,
  `Pulwama`,
  `Punalur`,
  `Punch`,
  `Pune`,
  `Punganur`,
  `Punjaipugalur`,
  `Puranpur`,
  `Purba Medinipur`,
  `Puri`,
  `Purna`,
  `Purnia`,
  `PurqUrban Agglomerationzi`,
  `Purulia`,
  `Purwa`,
  `Pusad`,
  `Puthuppally`,
  `Puttur`,
  `Qadian`,
  `Raayachuru`,
  `Rabkavi Banhatti`,
  `Radhanpur`,
  `Rae Bareli`,
  `Raebareli`,
  `Rafiganj`,
  `Raghogarh-Vijaypur`,
  `Raghunathganj`,
  `Raghunathpur`,
  `Rahatgarh`,
  `Rahuri`,
  `Raichur`,
  `Raigad`,
  `Raiganj`,
  `Raigarh`,
  `Raikot`,
  `Raipur`,
  `Rairangpur`,
  `Raisen`,
  `Raisinghnagar`,
  `Rajagangapur`,
  `Rajahmundry`,
  `Rajakhera`,
  `Rajaldesar`,
  `Rajam`,
  `Rajampet`,
  `Rajapalayam`,
  `Rajauri`,
  `Rajgarh`,
  `Rajgarh (Alwar)`,
  `Rajgarh (Churu)`,
  `Rajgir`,
  `Rajkot`,
  `Rajnandgaon`,
  `Rajpipla`,
  `Rajpura`,
  `Rajsamand`,
  `Rajula`,
  `Rajura`,
  `Ramabai Nagar (Kanpur Dehat)`,
  `Ramachandrapuram`,
  `Ramagundam`,
  `Ramanagara`,
  `Ramanagaram`,
  `Ramanathapuram`,
  `Ramban`,
  `Ramdurg`,
  `Rameshwaram`,
  `Ramganj Mandi`,
  `Ramgarh`,
  `Ramnagar`,
  `Ramngarh`,
  `Rampur`,
  `Rampur Maniharan`,
  `Rampura Phul`,
  `Rampurhat`,
  `Ramtek`,
  `Ranaghat`,
  `Ranavav`,
  `Ranchi`,
  `Ranebennuru`,
  `Rangia`,
  `Rania`,
  `Ranibennur`,
  `Ranipet`,
  `Rapar`,
  `Rasipuram`,
  `Rasra`,
  `Ratangarh`,
  `Rath`,
  `Ratia`,
  `Ratlam`,
  `Ratnagiri`,
  `Rau`,
  `Raurkela`,
  `Raver`,
  `Rawatbhata`,
  `Rawatsar`,
  `Raxaul Bazar`,
  `Rayachoti`,
  `Rayadurg`,
  `Rayagada`,
  `Reasi`,
  `Reengus`,
  `Rehli`,
  `Renigunta`,
  `Renukoot`,
  `Reoti`,
  `Repalle`,
  `Revelganj`,
  `Rewa`,
  `Rewari`,
  `Ri Bhoi`,
  `Rishikesh`,
  `Risod`,
  `Robertsganj`,
  `Robertson Pet`,
  `Rohtak`,
  `Rohtas`,
  `Ron`,
  `Roorkee`,
  `Rosera`,
  `Rudauli`,
  `Rudraprayag`,
  `Rudrapur`,
  `Rupnagar`,
  `SUrban Agglomerationr`,
  `Sabalgarh`,
  `Sabarkantha`,
  `Sadabad`,
  `Sadalagi`,
  `Sadasivpet`,
  `Sadri`,
  `Sadulpur`,
  `Sadulshahar`,
  `Safidon`,
  `Safipur`,
  `Sagar`,
  `Sagara`,
  `Sagwara`,
  `Saharanpur`,
  `Saharsa`,
  `Sahaspur`,
  `Sahaswan`,
  `Sahawar`,
  `Sahibganj`,
  `Sahjanwa`,
  `Saidpur`,
  `Saiha`,
  `Sailu`,
  `Sainthia`,
  `Sakaleshapura`,
  `Sakti`,
  `Salaya`,
  `Salem`,
  `Salur`,
  `Samalkha`,
  `Samalkot`,
  `Samana`,
  `Samastipur`,
  `Samba`,
  `Sambalpur`,
  `Sambhal`,
  `Sambhar`,
  `Samdhan`,
  `Samthar`,
  `Sanand`,
  `Sanawad`,
  `Sanchore`,
  `Sandi`,
  `Sandila`,
  `Sanduru`,
  `Sangamner`,
  `Sangareddy`,
  `Sangaria`,
  `Sangli`,
  `Sangole`,
  `Sangrur`,
  `Sankarankovil`,
  `Sankari`,
  `Sankeshwara`,
  `Sant Kabir Nagar`,
  `Sant Ravidas Nagar`,
  `Santipur`,
  `Saran`,
  `Sarangpur`,
  `Sardarshahar`,
  `Sardhana`,
  `Sarni`,
  `Sarsod`,
  `Sasaram`,
  `Sasvad`,
  `Satana`,
  `Satara`,
  `Sathyamangalam`,
  `Satna`,
  `Sattenapalle`,
  `Sattur`,
  `Saunda`,
  `Saundatti-Yellamma`,
  `Sausar`,
  `Savanur`,
  `Savarkundla`,
  `Savner`,
  `Sawai Madhopur`,
  `Sawantwadi`,
  `Sedam`,
  `Sehore`,
  `Senapati`,
  `Sendhwa`,
  `Seohara`,
  `Seoni`,
  `Seoni-Malwa`,
  `Seraikela Kharsawan`,
  `Serchhip`,
  `Shahabad`,
  `Shahabad, Hardoi`,
  `Shahabad, Rampur`,
  `Shahade`,
  `Shahbad`,
  `Shahdol`,
  `Shahganj`,
  `Shahjahanpur`,
  `Shahpur`,
  `Shahpura`,
  `Shajapur`,
  `Shamgarh`,
  `Shamli`,
  `Shamsabad, Agra`,
  `Shamsabad, Farrukhabad`,
  `Shegaon`,
  `Sheikhpura`,
  `Shendurjana`,
  `Shenkottai`,
  `Sheoganj`,
  `Sheohar`,
  `Sheopur`,
  `Sherghati`,
  `Sherkot`,
  `Shiggaon`,
  `Shikaripur`,
  `Shikarpur, Bulandshahr`,
  `Shikohabad`,
  `Shillong`,
  `Shimla`,
  `Shimoga`,
  `Shirdi`,
  `Shirpur-Warwade`,
  `Shirur`,
  `Shishgarh`,
  `Shivamogga`,
  `Shivpuri`,
  `Sholavandan`,
  `Sholingur`,
  `Shopian`,
  `Shoranur`,
  `Shravasti`,
  `Shrigonda`,
  `Shrirampur`,
  `Shrirangapattana`,
  `Shujalpur`,
  `Siana`,
  `Sibsagar`,
  `Siddharthnagar`,
  `Siddipet`,
  `Sidhi`,
  `Sidhpur`,
  `Sidlaghatta`,
  `Sihor`,
  `Sihora`,
  `Sikanderpur`,
  `Sikandra Rao`,
  `Sikandrabad`,
  `Sikar`,
  `Silao`,
  `Silapathar`,
  `Silchar`,
  `Siliguri`,
  `Sillod`,
  `Silvassa`,
  `Simdega`,
  `Sindagi`,
  `Sindhagi`,
  `Sindhnur`,
  `Sindhudurg`,
  `Singrauli`,
  `Sinnar`,
  `Sira`,
  `Sircilla`,
  `Sirhind Fatehgarh Sahib`,
  `Sirkali`,
  `Sirmaur`,
  `Sirohi`,
  `Sironj`,
  `Sirsa`,
  `Sirsaganj`,
  `Sirsi`,
  `Siruguppa`,
  `Sitamarhi`,
  `Sitapur`,
  `Sitarganj`,
  `Sivaganga`,
  `Sivagiri`,
  `Sivakasi`,
  `Siwan`,
  `Sohagpur`,
  `Sohna`,
  `Sojat`,
  `Solan`,
  `Solapur`,
  `Sonamukhi`,
  `Sonbhadra`,
  `Sonepur`,
  `Songadh`,
  `Sonipat`,
  `Sonitpur`,
  `Sopore`,
  `Soro`,
  `Soron`,
  `South 24 Parganas`,
  `South Delhi`,
  `South Garo Hills`,
  `South Goa`,
  `South Sikkim`,
  `South Tripura`,
  `South West Delhi`,
  `Soyagaon`,
  `Sri Madhopur`,
  `Sri Muktsar Sahib`,
  `Srikakulam`,
  `Srikalahasti`,
  `Srinagar`,
  `Srinivaspur`,
  `Srirampore`,
  `Srisailam Project (Right Flank Colony) Township`,
  `Srivilliputhur`,
  `Subarnapur (Sonepur)`,
  `Sugauli`,
  `Sujangarh`,
  `Sujanpur`,
  `Sullurpeta`,
  `Sultanganj`,
  `Sultanpur`,
  `Sumerpur`,
  `Sunabeda`,
  `Sunam`,
  `Sundargarh`,
  `Sundarnagar`,
  `Sundergarh`,
  `Supaul`,
  `Surandai`,
  `Surapura`,
  `Surat`,
  `Suratgarh`,
  `Surendranagar`,
  `Surguja`,
  `Suri`,
  `Suriyampalayam`,
  `Suryapet`,
  `Tadepalligudem`,
  `Tadpatri`,
  `Takhatgarh`,
  `Taki`,
  `Talaja`,
  `Talcher`,
  `Talegaon Dabhade`,
  `Talikota`,
  `Taliparamba`,
  `Talode`,
  `Talwara`,
  `Tamenglong`,
  `Tamluk`,
  `Tanda`,
  `Tandur`,
  `Tanuku`,
  `Tarakeswar`,
  `Tarana`,
  `Taranagar`,
  `Taraori`,
  `Tarbha`,
  `Tarikere`,
  `Tarn Taran`,
  `Tasgaon`,
  `Tawang`,
  `Tehri`,
  `Tehri Garhwal`,
  `Tekkalakote`,
  `Tenali`,
  `Tenkasi`,
  `Tenu dam-*****-Kathhara`,
  `Terdal`,
  `Tezpur`,
  `Thakurdwara`,
  `Thammampatti`,
  `Thana Bhawan`,
  `Thane`,
  `Thanesar`,
  `Thangadh`,
  `Thanjavur`,
  `Tharad`,
  `Tharamangalam`,
  `Tharangambadi`,
  `The Dangs`,
  `Theni`,
  `Theni Allinagaram`,
  `Thirumangalam`,
  `Thirupuvanam`,
  `Thiruthuraipoondi`,
  `Thiruvalla`,
  `Thiruvallur`,
  `Thiruvananthapuram`,
  `Thiruvarur`,
  `Thodupuzha`,
  `Thoothukudi`,
  `Thoubal`,
  `Thrissur`,
  `Thuraiyur`,
  `Tikamgarh`,
  `Tilda Newra`,
  `Tilhar`,
  `Tindivanam`,
  `Tinsukia`,
  `Tiptur`,
  `Tirap`,
  `Tirora`,
  `Tiruchendur`,
  `Tiruchengode`,
  `Tiruchirappalli`,
  `Tirukalukundram`,
  `Tirukkoyilur`,
  `Tirunelveli`,
  `Tirupathur`,
  `Tirupati`,
  `Tiruppur`,
  `Tirupur`,
  `Tirur`,
  `Tiruttani`,
  `Tiruvallur`,
  `Tiruvannamalai`,
  `Tiruvarur`,
  `Tiruvethipuram`,
  `Tiruvuru`,
  `Tirwaganj`,
  `Titlagarh`,
  `Tittakudi`,
  `Todabhim`,
  `Todaraisingh`,
  `Tohana`,
  `Tonk`,
  `Tuensang`,
  `Tuljapur`,
  `Tulsipur`,
  `Tumkur`,
  `Tumsar`,
  `Tundla`,
  `Tuni`,
  `Tura`,
  `Uchgaon`,
  `Udaipur`,
  `Udaipurwati`,
  `Udalguri`,
  `Udgir`,
  `Udhagamandalam`,
  `Udham Singh Nagar`,
  `Udhampur`,
  `Udumalaipettai`,
  `Udupi`,
  `Ujhani`,
  `Ujjain`,
  `Ukhrul`,
  `Umarga`,
  `Umaria`,
  `Umarkhed`,
  `Umbergaon`,
  `Umred`,
  `Umreth`,
  `Una`,
  `Unjha`,
  `Unnamalaikadai`,
  `Unnao`,
  `Upleta`,
  `Upper Siang`,
  `Upper Subansiri`,
  `Uran`,
  `Uran Islampur`,
  `Uravakonda`,
  `Urmar Tanda`,
  `Usilampatti`,
  `Uthamapalayam`,
  `Uthiramerur`,
  `Utraula`,
  `Uttar Dinajpur`,
  `Uttara Kannada`,
  `Uttarkashi`,
  `Vadakkuvalliyur`,
  `Vadalur`,
  `Vadgaon Kasba`,
  `Vadipatti`,
  `Vadnagar`,
  `Vadodara`,
  `Vaijapur`,
  `Vaikom`,
  `Vaishali`,
  `Valparai`,
  `Valsad`,
  `Vandavasi`,
  `Vaniyambadi`,
  `Vapi`,
  `Varanasi`,
  `Varkala`,
  `Vasai-Virar`,
  `Vatakara`,
  `Vedaranyam`,
  `Vellakoil`,
  `Vellore`,
  `Venkatagiri`,
  `Veraval`,
  `Vidisha`,
  `Vijainagar, Ajmer`,
  `Vijapur`,
  `Vijayapura`,
  `Vijayawada`,
  `Vijaypur`,
  `Vikarabad`,
  `Vikramasingapuram`,
  `Viluppuram`,
  `Vinukonda`,
  `Viramgam`,
  `Virudhachalam`,
  `Virudhunagar`,
  `Visakhapatnam`,
  `Visnagar`,
  `Viswanatham`,
  `Vita`,
  `Vizianagaram`,
  `Vrindavan`,
  `Vyara`,
  `Wadgaon Road`,
  `Wadhwan`,
  `Wadi`,
  `Wai`,
  `Wanaparthy`,
  `Wani`,
  `Wankaner`,
  `Wara Seoni`,
  `Warangal`,
  `Wardha`,
  `Warhapur`,
  `Warisaliganj`,
  `Warora`,
  `Warud`,
  `Washim`,
  `Wayanad`,
  `West Champaran`,
  `West Delhi`,
  `West Garo Hills`,
  `West Kameng`,
  `West Khasi Hills`,
  `West Siang`,
  `West Sikkim`,
  `West Singhbhum`,
  `West Tripura`,
  `Wokha`,
  `Yadgir`,
  `Yamuna Nagar`,
  `Yamunanagar`,
  `Yanam`,
  `Yavatmal`,
  `Yawal`,
  `Yellandu`,
  `Yemmiganur`,
  `Yerraguntla`,
  `Yevla`,
  `Zaidpur`,
  `Zamania`,
  `Zira`,
  `Zirakpur`,
  `Zunheboto`,
];
// export const cities = [
//   { value: `Achalpur`, label: `Achalpur` },
//   { value: `Achhnera`, label: `Achhnera` },
//   { value: `Adalaj`, label: `Adalaj` },
//   { value: `Adilabad`, label: `Adilabad` },
//   { value: `Adityapur`, label: `Adityapur` },
//   { value: `Adoni`, label: `Adoni` },
//   { value: `Adoor`, label: `Adoor` },
//   { value: `Adra`, label: `Adra` },
//   { value: `Adyar`, label: `Adyar` },
//   { value: `Afzalpur`, label: `Afzalpur` },
//   { value: `Agartala`, label: `Agartala` },
//   { value: `Agra`, label: `Agra` },
//   { value: `Ahmedabad`, label: `Ahmedabad` },
//   { value: `Ahmednagar`, label: `Ahmednagar` },
//   { value: `Aizawl`, label: `Aizawl` },
//   { value: `Ajitgarh (Mohali)`, label: `Ajitgarh (Mohali)` },
//   { value: `Ajmer`, label: `Ajmer` },
//   { value: `Akola`, label: `Akola` },
//   { value: `Akot`, label: `Akot` },
//   { value: `Alappuzha`, label: `Alappuzha` },
//   { value: `Aligarh`, label: `Aligarh` },
//   {
//     value: `AlipurdUrban Agglomerationr`,
//     label: `AlipurdUrban Agglomerationr`,
//   },
//   { value: `Alirajpur`, label: `Alirajpur` },
//   { value: `Allahabad`, label: `Allahabad` },
//   { value: `Almora`, label: `Almora` },
//   { value: `Alwar`, label: `Alwar` },
//   { value: `Amalapuram`, label: `Amalapuram` },
//   { value: `Amalner`, label: `Amalner` },
//   { value: `Ambala`, label: `Ambala` },
//   { value: `Ambedkar Nagar`, label: `Ambedkar Nagar` },
//   { value: `Ambejogai`, label: `Ambejogai` },
//   { value: `Ambikapur`, label: `Ambikapur` },
//   { value: `Amravati`, label: `Amravati` },
//   { value: `Amreli`, label: `Amreli` },
//   { value: `Amreli district`, label: `Amreli district` },
//   { value: `Amritsar`, label: `Amritsar` },
//   { value: `Amroha`, label: `Amroha` },
//   { value: `Anakapalle`, label: `Anakapalle` },
//   { value: `Anand`, label: `Anand` },
//   { value: `Anantapur`, label: `Anantapur` },
//   { value: `Anantnag`, label: `Anantnag` },
//   { value: `Angul`, label: `Angul` },
//   { value: `Anjangaon`, label: `Anjangaon` },
//   { value: `Anjar`, label: `Anjar` },
//   { value: `Anjaw`, label: `Anjaw` },
//   { value: `Ankleshwar`, label: `Ankleshwar` },
//   { value: `Anuppur`, label: `Anuppur` },
//   { value: `Arakkonam`, label: `Arakkonam` },
//   { value: `Arambagh`, label: `Arambagh` },
//   { value: `Araria`, label: `Araria` },
//   { value: `Ariyalur`, label: `Ariyalur` },
//   { value: `Arrah`, label: `Arrah` },
//   { value: `Arsikere`, label: `Arsikere` },
//   { value: `Aruppukkottai`, label: `Aruppukkottai` },
//   { value: `Arvi`, label: `Arvi` },
//   { value: `Arwal`, label: `Arwal` },
//   { value: `Asansol`, label: `Asansol` },
//   { value: `Asarganj`, label: `Asarganj` },
//   { value: `Ashok Nagar`, label: `Ashok Nagar` },
//   { value: `Athni`, label: `Athni` },
//   { value: `Attingal`, label: `Attingal` },
//   { value: `Auraiya`, label: `Auraiya` },
//   { value: `Aurangabad`, label: `Aurangabad` },
//   { value: `Azamgarh`, label: `Azamgarh` },
//   { value: `Badgam`, label: `Badgam` },
//   { value: `Bagaha`, label: `Bagaha` },
//   { value: `Bagalkot`, label: `Bagalkot` },
//   { value: `Bageshwar`, label: `Bageshwar` },
//   { value: `Bagpat`, label: `Bagpat` },
//   { value: `Bahadurgarh`, label: `Bahadurgarh` },
//   { value: `Baharampur`, label: `Baharampur` },
//   { value: `Bahraich`, label: `Bahraich` },
//   { value: `Baksa`, label: `Baksa` },
//   { value: `Balaghat`, label: `Balaghat` },
//   { value: `Balangir`, label: `Balangir` },
//   { value: `Balasore`, label: `Balasore` },
//   { value: `Baleshwar Town`, label: `Baleshwar Town` },
//   { value: `Ballari`, label: `Ballari` },
//   { value: `Ballia`, label: `Ballia` },
//   { value: `Balrampur`, label: `Balrampur` },
//   { value: `Balurghat`, label: `Balurghat` },
//   { value: `Banaskantha`, label: `Banaskantha` },
//   { value: `Banda`, label: `Banda` },
//   { value: `Bandipora`, label: `Bandipora` },
//   { value: `Bangalore Rural`, label: `Bangalore Rural` },
//   { value: `Bangalore Urban`, label: `Bangalore Urban` },
//   { value: `Banka`, label: `Banka` },
//   { value: `Bankura`, label: `Bankura` },
//   { value: `Banswara`, label: `Banswara` },
//   { value: `Bapatla`, label: `Bapatla` },
//   { value: `Barabanki`, label: `Barabanki` },
//   { value: `Baramula`, label: `Baramula` },
//   { value: `Baramulla`, label: `Baramulla` },
//   { value: `Baran`, label: `Baran` },
//   { value: `Barbil`, label: `Barbil` },
//   { value: `Bardhaman`, label: `Bardhaman` },
//   { value: `Bareilly`, label: `Bareilly` },
//   { value: `Bargarh`, label: `Bargarh` },
//   { value: `Bargarh (Baragarh)`, label: `Bargarh (Baragarh)` },
//   { value: `Barh`, label: `Barh` },
//   { value: `Baripada Town`, label: `Baripada Town` },
//   { value: `Barmer`, label: `Barmer` },
//   { value: `Barnala`, label: `Barnala` },
//   { value: `Barpeta`, label: `Barpeta` },
//   { value: `Barwani`, label: `Barwani` },
//   { value: `Bastar`, label: `Bastar` },
//   { value: `Basti`, label: `Basti` },
//   { value: `Batala`, label: `Batala` },
//   { value: `Bathinda`, label: `Bathinda` },
//   { value: `Beed`, label: `Beed` },
//   { value: `Begusarai`, label: `Begusarai` },
//   { value: `Belagavi`, label: `Belagavi` },
//   { value: `Belgaum`, label: `Belgaum` },
//   { value: `Bellampalle`, label: `Bellampalle` },
//   { value: `Bellary`, label: `Bellary` },
//   { value: `Belonia`, label: `Belonia` },
//   { value: `Bengaluru`, label: `Bengaluru` },
//   { value: `Bettiah`, label: `Bettiah` },
//   { value: `Betul`, label: `Betul` },
//   { value: `BhabUrban Agglomeration`, label: `BhabUrban Agglomeration` },
//   { value: `Bhadrachalam`, label: `Bhadrachalam` },
//   { value: `Bhadrak`, label: `Bhadrak` },
//   { value: `Bhagalpur`, label: `Bhagalpur` },
//   { value: `Bhainsa`, label: `Bhainsa` },
//   { value: `Bhandara`, label: `Bhandara` },
//   { value: `Bharatpur`, label: `Bharatpur` },
//   { value: `Bharuch`, label: `Bharuch` },
//   { value: `Bhatapara`, label: `Bhatapara` },
//   { value: `Bhavnagar`, label: `Bhavnagar` },
//   { value: `Bhawanipatna`, label: `Bhawanipatna` },
//   { value: `Bheemunipatnam`, label: `Bheemunipatnam` },
//   { value: `Bhilai Nagar`, label: `Bhilai Nagar` },
//   { value: `Bhilwara`, label: `Bhilwara` },
//   { value: `Bhimavaram`, label: `Bhimavaram` },
//   { value: `Bhind`, label: `Bhind` },
//   { value: `Bhiwandi`, label: `Bhiwandi` },
//   { value: `Bhiwani`, label: `Bhiwani` },
//   { value: `Bhojpur`, label: `Bhojpur` },
//   { value: `Bhongir`, label: `Bhongir` },
//   { value: `Bhopal`, label: `Bhopal` },
//   { value: `Bhubaneswar`, label: `Bhubaneswar` },
//   { value: `Bhuj`, label: `Bhuj` },
//   { value: `Bidar`, label: `Bidar` },
//   { value: `Bijapur`, label: `Bijapur` },
//   { value: `Bijnor`, label: `Bijnor` },
//   { value: `Bikaner`, label: `Bikaner` },
//   { value: `Bilaspur`, label: `Bilaspur` },
//   { value: `Birbhum`, label: `Birbhum` },
//   { value: `Bishnupur`, label: `Bishnupur` },
//   { value: `Bobbili`, label: `Bobbili` },
//   { value: `Bodhan`, label: `Bodhan` },
//   { value: `Bokaro`, label: `Bokaro` },
//   { value: `Bokaro Steel City`, label: `Bokaro Steel City` },
//   { value: `Bongaigaon`, label: `Bongaigaon` },
//   { value: `Bongaigaon City`, label: `Bongaigaon City` },
//   { value: `Boudh (Bauda)`, label: `Boudh (Bauda)` },
//   { value: `Brahmapur`, label: `Brahmapur` },
//   { value: `Budaun`, label: `Budaun` },
//   { value: `Bulandshahr`, label: `Bulandshahr` },
//   { value: `Buldhana`, label: `Buldhana` },
//   { value: `Bundi`, label: `Bundi` },
//   { value: `Burhanpur`, label: `Burhanpur` },
//   { value: `Buxar`, label: `Buxar` },
//   { value: `Byasanagar`, label: `Byasanagar` },
//   { value: `Cachar`, label: `Cachar` },
//   { value: `Central Delhi`, label: `Central Delhi` },
//   { value: `Chaibasa`, label: `Chaibasa` },
//   { value: `Chalakudy`, label: `Chalakudy` },
//   { value: `Chamarajnagar`, label: `Chamarajnagar` },
//   { value: `Chamba`, label: `Chamba` },
//   { value: `Chamoli`, label: `Chamoli` },
//   { value: `Champawat`, label: `Champawat` },
//   { value: `Champhai`, label: `Champhai` },
//   { value: `Chandauli`, label: `Chandauli` },
//   { value: `Chandausi`, label: `Chandausi` },
//   { value: `Chandel`, label: `Chandel` },
//   { value: `Chandigarh`, label: `Chandigarh` },
//   { value: `Chandrapur`, label: `Chandrapur` },
//   { value: `Changanassery`, label: `Changanassery` },
//   { value: `Changlang`, label: `Changlang` },
//   { value: `Charkhi Dadri`, label: `Charkhi Dadri` },
//   { value: `Chatra`, label: `Chatra` },
//   { value: `Chennai`, label: `Chennai` },
//   { value: `Cherthala`, label: `Cherthala` },
//   { value: `Chhapra`, label: `Chhapra` },
//   { value: `Chhatarpur`, label: `Chhatarpur` },
//   {
//     value: `Chhatrapati Shahuji Maharaj Nagar`,
//     label: `Chhatrapati Shahuji Maharaj Nagar`,
//   },
//   { value: `Chhindwara`, label: `Chhindwara` },
//   { value: `Chikkaballapur`, label: `Chikkaballapur` },
//   { value: `Chikkamagaluru`, label: `Chikkamagaluru` },
//   { value: `Chilakaluripet`, label: `Chilakaluripet` },
//   { value: `Chirala`, label: `Chirala` },
//   { value: `Chirang`, label: `Chirang` },
//   { value: `Chirkunda`, label: `Chirkunda` },
//   { value: `Chirmiri`, label: `Chirmiri` },
//   { value: `Chitradurga`, label: `Chitradurga` },
//   { value: `Chitrakoot`, label: `Chitrakoot` },
//   { value: `Chittoor`, label: `Chittoor` },
//   { value: `Chittorgarh`, label: `Chittorgarh` },
//   { value: `Chittur-Thathamangalam`, label: `Chittur-Thathamangalam` },
//   { value: `Churachandpur`, label: `Churachandpur` },
//   { value: `Churu`, label: `Churu` },
//   { value: `Coimbatore`, label: `Coimbatore` },
//   { value: `Cooch Behar`, label: `Cooch Behar` },
//   { value: `Cuddalore`, label: `Cuddalore` },
//   { value: `Cuttack`, label: `Cuttack` },
//   { value: `Dadra and Nagar Haveli`, label: `Dadra and Nagar Haveli` },
//   { value: `Dahod`, label: `Dahod` },
//   { value: `Dakshin Dinajpur`, label: `Dakshin Dinajpur` },
//   { value: `Dakshina Kannada`, label: `Dakshina Kannada` },
//   { value: `Dalli-Rajhara`, label: `Dalli-Rajhara` },
//   { value: `Daman`, label: `Daman` },
//   { value: `Damoh`, label: `Damoh` },
//   { value: `Dantewada`, label: `Dantewada` },
//   { value: `Darbhanga`, label: `Darbhanga` },
//   { value: `Darjeeling`, label: `Darjeeling` },
//   { value: `Darjiling`, label: `Darjiling` },
//   { value: `Darrang`, label: `Darrang` },
//   { value: `Datia`, label: `Datia` },
//   { value: `Dausa`, label: `Dausa` },
//   { value: `Davanagere`, label: `Davanagere` },
//   { value: `Debagarh (Deogarh)`, label: `Debagarh (Deogarh)` },
//   { value: `Deesa`, label: `Deesa` },
//   { value: `Dehradun`, label: `Dehradun` },
//   { value: `Dehri-on-Sone`, label: `Dehri-on-Sone` },
//   { value: `Delhi`, label: `Delhi` },
//   { value: `Deoghar`, label: `Deoghar` },
//   { value: `Deoria`, label: `Deoria` },
//   { value: `Dewas`, label: `Dewas` },
//   { value: `Dhalai`, label: `Dhalai` },
//   { value: `Dhamtari`, label: `Dhamtari` },
//   { value: `Dhanbad`, label: `Dhanbad` },
//   { value: `Dhar`, label: `Dhar` },
//   { value: `Dharmanagar`, label: `Dharmanagar` },
//   { value: `Dharmapuri`, label: `Dharmapuri` },
//   { value: `Dharmavaram`, label: `Dharmavaram` },
//   { value: `Dharwad`, label: `Dharwad` },
//   { value: `Dhemaji`, label: `Dhemaji` },
//   { value: `Dhenkanal`, label: `Dhenkanal` },
//   { value: `Dholpur`, label: `Dholpur` },
//   { value: `Dhoraji`, label: `Dhoraji` },
//   { value: `Dhubri`, label: `Dhubri` },
//   { value: `Dhule`, label: `Dhule` },
//   { value: `Dhuri`, label: `Dhuri` },
//   { value: `Dibang Valley`, label: `Dibang Valley` },
//   { value: `Dibrugarh`, label: `Dibrugarh` },
//   { value: `Dima Hasao`, label: `Dima Hasao` },
//   { value: `Dimapur`, label: `Dimapur` },
//   { value: `Dindigul`, label: `Dindigul` },
//   { value: `Dindori`, label: `Dindori` },
//   { value: `Diphu`, label: `Diphu` },
//   { value: `Diu`, label: `Diu` },
//   { value: `Doda`, label: `Doda` },
//   { value: `Dumka`, label: `Dumka` },
//   { value: `Dumraon`, label: `Dumraon` },
//   { value: `Dungapur`, label: `Dungapur` },
//   { value: `Durg`, label: `Durg` },
//   { value: `East Champaran`, label: `East Champaran` },
//   { value: `East Delhi`, label: `East Delhi` },
//   { value: `East Garo Hills`, label: `East Garo Hills` },
//   { value: `East Khasi Hills`, label: `East Khasi Hills` },
//   { value: `East Siang`, label: `East Siang` },
//   { value: `East Sikkim`, label: `East Sikkim` },
//   { value: `East Singhbhum`, label: `East Singhbhum` },
//   { value: `Eluru`, label: `Eluru` },
//   { value: `English Bazar`, label: `English Bazar` },
//   { value: `Ernakulam`, label: `Ernakulam` },
//   { value: `Erode`, label: `Erode` },
//   { value: `Etah`, label: `Etah` },
//   { value: `Etawah`, label: `Etawah` },
//   { value: `Faizabad`, label: `Faizabad` },
//   { value: `Faridabad`, label: `Faridabad` },
//   { value: `Faridkot`, label: `Faridkot` },
//   { value: `Farooqnagar`, label: `Farooqnagar` },
//   { value: `Farrukhabad`, label: `Farrukhabad` },
//   { value: `Fatehabad`, label: `Fatehabad` },
//   { value: `Fatehgarh Sahib`, label: `Fatehgarh Sahib` },
//   { value: `Fatehpur`, label: `Fatehpur` },
//   { value: `Fatehpur Sikri`, label: `Fatehpur Sikri` },
//   { value: `Fazilka`, label: `Fazilka` },
//   { value: `Firozabad`, label: `Firozabad` },
//   { value: `Firozpur`, label: `Firozpur` },
//   { value: `Firozpur Cantt.`, label: `Firozpur Cantt.` },
//   { value: `Forbesganj`, label: `Forbesganj` },
//   { value: `Gadag`, label: `Gadag` },
//   { value: `Gadchiroli`, label: `Gadchiroli` },
//   { value: `Gadwal`, label: `Gadwal` },
//   { value: `Gajapati`, label: `Gajapati` },
//   { value: `Ganderbal`, label: `Ganderbal` },
//   { value: `Gandhinagar`, label: `Gandhinagar` },
//   { value: `Ganganagar`, label: `Ganganagar` },
//   { value: `Gangarampur`, label: `Gangarampur` },
//   { value: `Ganjam`, label: `Ganjam` },
//   { value: `Ganjbasoda`, label: `Ganjbasoda` },
//   { value: `Garhwa`, label: `Garhwa` },
//   { value: `Gautam Buddh Nagar`, label: `Gautam Buddh Nagar` },
//   { value: `Gaya`, label: `Gaya` },
//   { value: `Ghaziabad`, label: `Ghaziabad` },
//   { value: `Ghazipur`, label: `Ghazipur` },
//   { value: `Giridih`, label: `Giridih` },
//   { value: `Goalpara`, label: `Goalpara` },
//   { value: `Gobichettipalayam`, label: `Gobichettipalayam` },
//   { value: `Gobindgarh`, label: `Gobindgarh` },
//   { value: `Godda`, label: `Godda` },
//   { value: `Godhra`, label: `Godhra` },
//   { value: `Gohana`, label: `Gohana` },
//   { value: `Gokak`, label: `Gokak` },
//   { value: `Golaghat`, label: `Golaghat` },
//   { value: `Gonda`, label: `Gonda` },
//   { value: `Gondia`, label: `Gondia` },
//   { value: `Gooty`, label: `Gooty` },
//   { value: `Gopalganj`, label: `Gopalganj` },
//   { value: `Gorakhpur`, label: `Gorakhpur` },
//   { value: `Gudivada`, label: `Gudivada` },
//   { value: `Gudur`, label: `Gudur` },
//   { value: `Gulbarga`, label: `Gulbarga` },
//   { value: `Gumia`, label: `Gumia` },
//   { value: `Gumla`, label: `Gumla` },
//   { value: `Guna`, label: `Guna` },
//   { value: `Guntakal`, label: `Guntakal` },
//   { value: `Guntur`, label: `Guntur` },
//   { value: `Gurdaspur`, label: `Gurdaspur` },
//   { value: `Gurgaon`, label: `Gurgaon` },
//   { value: `Guruvayoor`, label: `Guruvayoor` },
//   { value: `Guwahati`, label: `Guwahati` },
//   { value: `Gwalior`, label: `Gwalior` },
//   { value: `Habra`, label: `Habra` },
//   { value: `Hailakandi`, label: `Hailakandi` },
//   { value: `Hajipur`, label: `Hajipur` },
//   { value: `Haldwani-*****-Kathgodam`, label: `Haldwani-*****-Kathgodam` },
//   { value: `Hamirpur`, label: `Hamirpur` },
//   { value: `Hansi`, label: `Hansi` },
//   { value: `Hanumangarh`, label: `Hanumangarh` },
//   { value: `Hapur`, label: `Hapur` },
//   { value: `Harda`, label: `Harda` },
//   { value: `Hardoi`, label: `Hardoi` },
//   { value: `Hardoi `, label: `Hardoi ` },
//   { value: `Hardwar`, label: `Hardwar` },
//   { value: `Haridwar`, label: `Haridwar` },
//   { value: `Hassan`, label: `Hassan` },
//   { value: `Haveri district`, label: `Haveri district` },
//   { value: `Hazaribag`, label: `Hazaribag` },
//   { value: `Hindupur`, label: `Hindupur` },
//   { value: `Hingoli`, label: `Hingoli` },
//   { value: `Hisar`, label: `Hisar` },
//   { value: `Hissar`, label: `Hissar` },
//   { value: `Hooghly`, label: `Hooghly` },
//   { value: `Hoshangabad`, label: `Hoshangabad` },
//   { value: `Hoshiarpur`, label: `Hoshiarpur` },
//   { value: `Howrah`, label: `Howrah` },
//   { value: `Hubli-Dharwad`, label: `Hubli-Dharwad` },
//   { value: `Hugli-Chinsurah`, label: `Hugli-Chinsurah` },
//   { value: `Hyderabad`, label: `Hyderabad` },
//   { value: `Ichalkaranji`, label: `Ichalkaranji` },
//   { value: `Idukki`, label: `Idukki` },
//   { value: `Imphal`, label: `Imphal` },
//   { value: `Imphal East`, label: `Imphal East` },
//   { value: `Imphal West`, label: `Imphal West` },
//   { value: `Indore`, label: `Indore` },
//   { value: `Itarsi`, label: `Itarsi` },
//   { value: `Jabalpur`, label: `Jabalpur` },
//   { value: `Jagatsinghpur`, label: `Jagatsinghpur` },
//   { value: `Jagdalpur`, label: `Jagdalpur` },
//   { value: `Jaggaiahpet`, label: `Jaggaiahpet` },
//   { value: `Jagraon`, label: `Jagraon` },
//   { value: `Jagtial`, label: `Jagtial` },
//   { value: `Jaintia Hills`, label: `Jaintia Hills` },
//   { value: `Jaipur`, label: `Jaipur` },
//   { value: `Jaisalmer`, label: `Jaisalmer` },
//   { value: `Jajpur`, label: `Jajpur` },
//   { value: `Jalandhar`, label: `Jalandhar` },
//   { value: `Jalandhar Cantt.`, label: `Jalandhar Cantt.` },
//   { value: `Jalaun`, label: `Jalaun` },
//   { value: `Jalgaon`, label: `Jalgaon` },
//   { value: `Jalna`, label: `Jalna` },
//   { value: `Jalore`, label: `Jalore` },
//   { value: `Jalpaiguri`, label: `Jalpaiguri` },
//   { value: `Jamalpur`, label: `Jamalpur` },
//   { value: `Jammalamadugu`, label: `Jammalamadugu` },
//   { value: `Jammu`, label: `Jammu` },
//   { value: `Jamnagar`, label: `Jamnagar` },
//   { value: `Jamshedpur`, label: `Jamshedpur` },
//   { value: `Jamtara`, label: `Jamtara` },
//   { value: `Jamui`, label: `Jamui` },
//   { value: `Jangaon`, label: `Jangaon` },
//   { value: `Janjgir-Champa`, label: `Janjgir-Champa` },
//   { value: `Jashpur`, label: `Jashpur` },
//   { value: `Jatani`, label: `Jatani` },
//   { value: `Jaunpur district`, label: `Jaunpur district` },
//   { value: `Jehanabad`, label: `Jehanabad` },
//   { value: `Jhabua`, label: `Jhabua` },
//   { value: `Jhajjar`, label: `Jhajjar` },
//   { value: `Jhalawar`, label: `Jhalawar` },
//   { value: `Jhansi`, label: `Jhansi` },
//   { value: `Jhargram`, label: `Jhargram` },
//   { value: `Jharsuguda`, label: `Jharsuguda` },
//   { value: `Jhumri Tilaiya`, label: `Jhumri Tilaiya` },
//   { value: `Jhunjhunu`, label: `Jhunjhunu` },
//   { value: `Jind`, label: `Jind` },
//   { value: `Jodhpur`, label: `Jodhpur` },
//   { value: `Jorhat`, label: `Jorhat` },
//   { value: `Junagadh`, label: `Junagadh` },
//   { value: `Jyotiba Phule Nagar`, label: `Jyotiba Phule Nagar` },
//   {
//     value: `Kabirdham (formerly Kawardha)`,
//     label: `Kabirdham (formerly Kawardha)`,
//   },
//   { value: `Kadapa`, label: `Kadapa` },
//   { value: `Kadi`, label: `Kadi` },
//   { value: `Kadiri`, label: `Kadiri` },
//   { value: `Kagaznagar`, label: `Kagaznagar` },
//   { value: `Kailasahar`, label: `Kailasahar` },
//   { value: `Kaimur`, label: `Kaimur` },
//   { value: `Kaithal`, label: `Kaithal` },
//   { value: `Kakinada`, label: `Kakinada` },
//   { value: `Kalahandi`, label: `Kalahandi` },
//   { value: `Kalimpong`, label: `Kalimpong` },
//   { value: `Kalpi`, label: `Kalpi` },
//   { value: `Kalyan-Dombivali`, label: `Kalyan-Dombivali` },
//   { value: `Kamareddy`, label: `Kamareddy` },
//   { value: `Kamrup`, label: `Kamrup` },
//   { value: `Kamrup Metropolitan`, label: `Kamrup Metropolitan` },
//   { value: `Kancheepuram`, label: `Kancheepuram` },
//   { value: `Kanchipuram`, label: `Kanchipuram` },
//   { value: `Kandhamal`, label: `Kandhamal` },
//   { value: `Kandukur`, label: `Kandukur` },
//   { value: `Kangra`, label: `Kangra` },
//   { value: `Kanhangad`, label: `Kanhangad` },
//   { value: `Kanker`, label: `Kanker` },
//   { value: `Kannauj`, label: `Kannauj` },
//   { value: `Kannur`, label: `Kannur` },
//   { value: `Kanpur`, label: `Kanpur` },
//   { value: `Kanshi Ram Nagar`, label: `Kanshi Ram Nagar` },
//   { value: `Kanyakumari`, label: `Kanyakumari` },
//   { value: `Kapadvanj`, label: `Kapadvanj` },
//   { value: `Kapurthala`, label: `Kapurthala` },
//   { value: `Karaikal`, label: `Karaikal` },
//   { value: `Karauli`, label: `Karauli` },
//   { value: `Karbi Anglong`, label: `Karbi Anglong` },
//   { value: `Kargil`, label: `Kargil` },
//   { value: `Karimganj`, label: `Karimganj` },
//   { value: `Karimnagar`, label: `Karimnagar` },
//   { value: `Karjat`, label: `Karjat` },
//   { value: `Karnal`, label: `Karnal` },
//   { value: `Karur`, label: `Karur` },
//   { value: `Karwar`, label: `Karwar` },
//   { value: `Kasaragod`, label: `Kasaragod` },
//   { value: `Kashipur`, label: `Kashipur` },
//   { value: `KathUrban Agglomeration`, label: `KathUrban Agglomeration` },
//   { value: `Kathua`, label: `Kathua` },
//   { value: `Katihar`, label: `Katihar` },
//   { value: `Katni`, label: `Katni` },
//   { value: `Kaushambi`, label: `Kaushambi` },
//   { value: `Kavali`, label: `Kavali` },
//   { value: `Kayamkulam`, label: `Kayamkulam` },
//   { value: `Kendrapara`, label: `Kendrapara` },
//   { value: `Kendujhar`, label: `Kendujhar` },
//   { value: `Kendujhar (Keonjhar)`, label: `Kendujhar (Keonjhar)` },
//   { value: `Keshod`, label: `Keshod` },
//   { value: `Khagaria`, label: `Khagaria` },
//   { value: `Khair`, label: `Khair` },
//   { value: `Khambhat`, label: `Khambhat` },
//   { value: `Khammam`, label: `Khammam` },
//   { value: `Khandwa (East Nimar)`, label: `Khandwa (East Nimar)` },
//   { value: `Khanna`, label: `Khanna` },
//   { value: `Kharagpur`, label: `Kharagpur` },
//   { value: `Kharar`, label: `Kharar` },
//   { value: `Khargone (West Nimar)`, label: `Khargone (West Nimar)` },
//   { value: `Kheda`, label: `Kheda` },
//   { value: `Khordha`, label: `Khordha` },
//   { value: `Khowai`, label: `Khowai` },
//   { value: `Khunti`, label: `Khunti` },
//   { value: `Kinnaur`, label: `Kinnaur` },
//   { value: `Kishanganj`, label: `Kishanganj` },
//   { value: `Kishtwar`, label: `Kishtwar` },
//   { value: `Kochi`, label: `Kochi` },
//   { value: `Kodagu`, label: `Kodagu` },
//   { value: `Koderma`, label: `Koderma` },
//   { value: `Kodungallur`, label: `Kodungallur` },
//   { value: `Kohima`, label: `Kohima` },
//   { value: `Kokrajhar`, label: `Kokrajhar` },
//   { value: `Kolar`, label: `Kolar` },
//   { value: `Kolasib`, label: `Kolasib` },
//   { value: `Kolhapur`, label: `Kolhapur` },
//   { value: `Kolkata`, label: `Kolkata` },
//   { value: `Kollam`, label: `Kollam` },
//   { value: `Koppal`, label: `Koppal` },
//   { value: `Koraput`, label: `Koraput` },
//   { value: `Koratla`, label: `Koratla` },
//   { value: `Korba`, label: `Korba` },
//   { value: `Koriya`, label: `Koriya` },
//   { value: `Kot Kapura`, label: `Kot Kapura` },
//   { value: `Kota`, label: `Kota` },
//   { value: `Kothagudem`, label: `Kothagudem` },
//   { value: `Kottayam`, label: `Kottayam` },
//   { value: `Kovvur`, label: `Kovvur` },
//   { value: `Koyilandy`, label: `Koyilandy` },
//   { value: `Kozhikode`, label: `Kozhikode` },
//   { value: `Krishna`, label: `Krishna` },
//   { value: `Kulgam`, label: `Kulgam` },
//   { value: `Kullu`, label: `Kullu` },
//   { value: `Kunnamkulam`, label: `Kunnamkulam` },
//   { value: `Kupwara`, label: `Kupwara` },
//   { value: `Kurnool`, label: `Kurnool` },
//   { value: `Kurukshetra`, label: `Kurukshetra` },
//   { value: `Kurung Kumey`, label: `Kurung Kumey` },
//   { value: `Kushinagar`, label: `Kushinagar` },
//   { value: `Kutch`, label: `Kutch` },
//   { value: `Kyathampalle`, label: `Kyathampalle` },
//   { value: `Lachhmangarh`, label: `Lachhmangarh` },
//   { value: `Ladnu`, label: `Ladnu` },
//   { value: `Ladwa`, label: `Ladwa` },
//   { value: `Lahar`, label: `Lahar` },
//   { value: `Laharpur`, label: `Laharpur` },
//   { value: `Lahaul and Spiti`, label: `Lahaul and Spiti` },
//   { value: `Lakheri`, label: `Lakheri` },
//   { value: `Lakhimpur`, label: `Lakhimpur` },
//   { value: `Lakhimpur Kheri`, label: `Lakhimpur Kheri` },
//   { value: `Lakhisarai`, label: `Lakhisarai` },
//   { value: `Lakshmeshwar`, label: `Lakshmeshwar` },
//   { value: `Lal Gopalganj Nindaura`, label: `Lal Gopalganj Nindaura` },
//   { value: `Lalganj`, label: `Lalganj` },
//   { value: `Lalgudi`, label: `Lalgudi` },
//   { value: `Lalitpur`, label: `Lalitpur` },
//   { value: `Lalsot`, label: `Lalsot` },
//   { value: `Lanka`, label: `Lanka` },
//   { value: `Lar`, label: `Lar` },
//   { value: `Latehar`, label: `Latehar` },
//   { value: `Lathi`, label: `Lathi` },
//   { value: `Latur`, label: `Latur` },
//   { value: `Lawngtlai`, label: `Lawngtlai` },
//   { value: `Leh`, label: `Leh` },
//   { value: `Lilong`, label: `Lilong` },
//   { value: `Limbdi`, label: `Limbdi` },
//   { value: `Lingsugur`, label: `Lingsugur` },
//   { value: `Loha`, label: `Loha` },
//   { value: `Lohardaga`, label: `Lohardaga` },
//   { value: `Lohit`, label: `Lohit` },
//   { value: `Lonar`, label: `Lonar` },
//   { value: `Lonavla`, label: `Lonavla` },
//   { value: `Longowal`, label: `Longowal` },
//   { value: `Loni`, label: `Loni` },
//   { value: `Losal`, label: `Losal` },
//   { value: `Lower Dibang Valley`, label: `Lower Dibang Valley` },
//   { value: `Lower Subansiri`, label: `Lower Subansiri` },
//   { value: `Lucknow`, label: `Lucknow` },
//   { value: `Ludhiana`, label: `Ludhiana` },
//   { value: `Lumding`, label: `Lumding` },
//   { value: `Lunawada`, label: `Lunawada` },
//   { value: `Lunglei`, label: `Lunglei` },
//   { value: `Macherla`, label: `Macherla` },
//   { value: `Machilipatnam`, label: `Machilipatnam` },
//   { value: `Madanapalle`, label: `Madanapalle` },
//   { value: `Maddur`, label: `Maddur` },
//   { value: `Madhepura`, label: `Madhepura` },
//   { value: `Madhubani`, label: `Madhubani` },
//   { value: `Madhugiri`, label: `Madhugiri` },
//   { value: `Madhupur`, label: `Madhupur` },
//   { value: `Madikeri`, label: `Madikeri` },
//   { value: `Madurai`, label: `Madurai` },
//   { value: `Magadi`, label: `Magadi` },
//   { value: `Mahad`, label: `Mahad` },
//   { value: `Mahalingapura`, label: `Mahalingapura` },
//   { value: `Mahamaya Nagar`, label: `Mahamaya Nagar` },
//   { value: `Maharajganj`, label: `Maharajganj` },
//   { value: `Maharajpur`, label: `Maharajpur` },
//   { value: `Mahasamund`, label: `Mahasamund` },
//   { value: `Mahbubnagar`, label: `Mahbubnagar` },
//   { value: `Mahe`, label: `Mahe` },
//   { value: `Mahemdabad`, label: `Mahemdabad` },
//   { value: `Mahendragarh`, label: `Mahendragarh` },
//   { value: `Mahesana`, label: `Mahesana` },
//   { value: `Mahidpur`, label: `Mahidpur` },
//   { value: `Mahnar Bazar`, label: `Mahnar Bazar` },
//   { value: `Mahoba`, label: `Mahoba` },
//   { value: `Mahuva`, label: `Mahuva` },
//   { value: `Maihar`, label: `Maihar` },
//   { value: `Mainaguri`, label: `Mainaguri` },
//   { value: `Mainpuri`, label: `Mainpuri` },
//   { value: `Makhdumpur`, label: `Makhdumpur` },
//   { value: `Makrana`, label: `Makrana` },
//   { value: `Malaj Khand`, label: `Malaj Khand` },
//   { value: `Malappuram`, label: `Malappuram` },
//   { value: `Malavalli`, label: `Malavalli` },
//   { value: `Malda`, label: `Malda` },
//   { value: `Maldah`, label: `Maldah` },
//   { value: `Malegaon`, label: `Malegaon` },
//   { value: `Malerkotla`, label: `Malerkotla` },
//   { value: `Malkangiri`, label: `Malkangiri` },
//   { value: `Malkapur`, label: `Malkapur` },
//   { value: `Malout`, label: `Malout` },
//   { value: `Malpura`, label: `Malpura` },
//   { value: `Malur`, label: `Malur` },
//   { value: `Mamit`, label: `Mamit` },
//   { value: `Manachanallur`, label: `Manachanallur` },
//   { value: `Manasa`, label: `Manasa` },
//   { value: `Manavadar`, label: `Manavadar` },
//   { value: `Manawar`, label: `Manawar` },
//   { value: `Mancherial`, label: `Mancherial` },
//   { value: `Mandalgarh`, label: `Mandalgarh` },
//   { value: `Mandamarri`, label: `Mandamarri` },
//   { value: `Mandapeta`, label: `Mandapeta` },
//   { value: `Mandawa`, label: `Mandawa` },
//   { value: `Mandi`, label: `Mandi` },
//   { value: `Mandi Dabwali`, label: `Mandi Dabwali` },
//   { value: `Mandideep`, label: `Mandideep` },
//   { value: `Mandla`, label: `Mandla` },
//   { value: `Mandsaur`, label: `Mandsaur` },
//   { value: `Mandvi`, label: `Mandvi` },
//   { value: `Mandya`, label: `Mandya` },
//   { value: `Manendragarh`, label: `Manendragarh` },
//   { value: `Maner`, label: `Maner` },
//   { value: `Mangaldoi`, label: `Mangaldoi` },
//   { value: `Mangaluru`, label: `Mangaluru` },
//   { value: `Mangalvedhe`, label: `Mangalvedhe` },
//   { value: `Manglaur`, label: `Manglaur` },
//   { value: `Mangrol`, label: `Mangrol` },
//   { value: `Mangrulpir`, label: `Mangrulpir` },
//   { value: `Manihari`, label: `Manihari` },
//   { value: `Manjlegaon`, label: `Manjlegaon` },
//   { value: `Mankachar`, label: `Mankachar` },
//   { value: `Manmad`, label: `Manmad` },
//   { value: `Mansa`, label: `Mansa` },
//   { value: `Manuguru`, label: `Manuguru` },
//   { value: `Manvi`, label: `Manvi` },
//   { value: `Manwath`, label: `Manwath` },
//   { value: `Mapusa`, label: `Mapusa` },
//   { value: `Margao`, label: `Margao` },
//   { value: `Margherita`, label: `Margherita` },
//   { value: `Marhaura`, label: `Marhaura` },
//   { value: `Mariani`, label: `Mariani` },
//   { value: `Marigaon`, label: `Marigaon` },
//   { value: `Markapur`, label: `Markapur` },
//   { value: `Marmagao`, label: `Marmagao` },
//   { value: `Masaurhi`, label: `Masaurhi` },
//   { value: `Mathabhanga`, label: `Mathabhanga` },
//   { value: `Mathura`, label: `Mathura` },
//   { value: `Mattannur`, label: `Mattannur` },
//   { value: `Mau`, label: `Mau` },
//   { value: `Mauganj`, label: `Mauganj` },
//   { value: `Mavelikkara`, label: `Mavelikkara` },
//   { value: `Mavoor`, label: `Mavoor` },
//   { value: `Mayang Imphal`, label: `Mayang Imphal` },
//   { value: `Mayurbhanj`, label: `Mayurbhanj` },
//   { value: `Medak`, label: `Medak` },
//   { value: `Medininagar (Daltonganj)`, label: `Medininagar (Daltonganj)` },
//   { value: `Medinipur`, label: `Medinipur` },
//   { value: `Meerut`, label: `Meerut` },
//   { value: `Mehkar`, label: `Mehkar` },
//   { value: `Mehsana`, label: `Mehsana` },
//   { value: `Memari`, label: `Memari` },
//   { value: `Merta City`, label: `Merta City` },
//   { value: `Mewat`, label: `Mewat` },
//   { value: `Mhaswad`, label: `Mhaswad` },
//   { value: `Mhow Cantonment`, label: `Mhow Cantonment` },
//   { value: `Mhowgaon`, label: `Mhowgaon` },
//   { value: `Mihijam`, label: `Mihijam` },
//   { value: `Mira-Bhayandar`, label: `Mira-Bhayandar` },
//   { value: `Mirganj`, label: `Mirganj` },
//   { value: `Miryalaguda`, label: `Miryalaguda` },
//   { value: `Mirzapur`, label: `Mirzapur` },
//   { value: `Modasa`, label: `Modasa` },
//   { value: `Modinagar`, label: `Modinagar` },
//   { value: `Moga`, label: `Moga` },
//   { value: `Mohali`, label: `Mohali` },
//   { value: `Mokameh`, label: `Mokameh` },
//   { value: `Mokokchung`, label: `Mokokchung` },
//   { value: `Mon`, label: `Mon` },
//   { value: `Monoharpur`, label: `Monoharpur` },
//   { value: `Moradabad`, label: `Moradabad` },
//   { value: `Morena`, label: `Morena` },
//   { value: `Morinda, India`, label: `Morinda, India` },
//   { value: `Morshi`, label: `Morshi` },
//   { value: `Morvi`, label: `Morvi` },
//   { value: `Motihari`, label: `Motihari` },
//   { value: `Motipur`, label: `Motipur` },
//   { value: `Mount Abu`, label: `Mount Abu` },
//   { value: `Mudabidri`, label: `Mudabidri` },
//   { value: `Mudalagi`, label: `Mudalagi` },
//   { value: `Muddebihal`, label: `Muddebihal` },
//   { value: `Mudhol`, label: `Mudhol` },
//   { value: `Mukerian`, label: `Mukerian` },
//   { value: `Mukhed`, label: `Mukhed` },
//   { value: `Muktsar`, label: `Muktsar` },
//   { value: `Mul`, label: `Mul` },
//   { value: `Mulbagal`, label: `Mulbagal` },
//   { value: `Multai`, label: `Multai` },
//   { value: `Mumbai`, label: `Mumbai` },
//   { value: `Mumbai City`, label: `Mumbai City` },
//   { value: `Mumbai suburban`, label: `Mumbai suburban` },
//   { value: `Mundargi`, label: `Mundargi` },
//   { value: `Mundi`, label: `Mundi` },
//   { value: `Mungeli`, label: `Mungeli` },
//   { value: `Munger`, label: `Munger` },
//   { value: `Murliganj`, label: `Murliganj` },
//   { value: `Murshidabad`, label: `Murshidabad` },
//   { value: `Murtijapur`, label: `Murtijapur` },
//   { value: `Murwara (Katni)`, label: `Murwara (Katni)` },
//   { value: `Musabani`, label: `Musabani` },
//   { value: `Mussoorie`, label: `Mussoorie` },
//   { value: `Muvattupuzha`, label: `Muvattupuzha` },
//   { value: `Muzaffarnagar`, label: `Muzaffarnagar` },
//   { value: `Muzaffarpur`, label: `Muzaffarpur` },
//   { value: `Mysore`, label: `Mysore` },
//   { value: `Nabadwip`, label: `Nabadwip` },
//   { value: `Nabarangapur`, label: `Nabarangapur` },
//   { value: `Nabarangpur`, label: `Nabarangpur` },
//   { value: `Nabha`, label: `Nabha` },
//   { value: `Nadbai`, label: `Nadbai` },
//   { value: `Nadia`, label: `Nadia` },
//   { value: `Nadiad`, label: `Nadiad` },
//   { value: `Nagaon`, label: `Nagaon` },
//   { value: `Nagapattinam`, label: `Nagapattinam` },
//   { value: `Nagar`, label: `Nagar` },
//   { value: `Nagari`, label: `Nagari` },
//   { value: `Nagarkurnool`, label: `Nagarkurnool` },
//   { value: `Nagaur`, label: `Nagaur` },
//   { value: `Nagda`, label: `Nagda` },
//   { value: `Nagercoil`, label: `Nagercoil` },
//   { value: `Nagina`, label: `Nagina` },
//   { value: `Nagla`, label: `Nagla` },
//   { value: `Nagpur`, label: `Nagpur` },
//   { value: `Nahan`, label: `Nahan` },
//   { value: `Naharlagun`, label: `Naharlagun` },
//   { value: `Naidupet`, label: `Naidupet` },
//   { value: `Naihati`, label: `Naihati` },
//   { value: `Naila Janjgir`, label: `Naila Janjgir` },
//   { value: `Nainital`, label: `Nainital` },
//   { value: `Nainpur`, label: `Nainpur` },
//   { value: `Najibabad`, label: `Najibabad` },
//   { value: `Nakodar`, label: `Nakodar` },
//   { value: `Nakur`, label: `Nakur` },
//   { value: `Nalanda`, label: `Nalanda` },
//   { value: `Nalbari`, label: `Nalbari` },
//   { value: `Nalgonda`, label: `Nalgonda` },
//   { value: `Namagiripettai`, label: `Namagiripettai` },
//   { value: `Namakkal`, label: `Namakkal` },
//   { value: `Nanded`, label: `Nanded` },
//   { value: `Nanded-Waghala`, label: `Nanded-Waghala` },
//   { value: `Nandgaon`, label: `Nandgaon` },
//   { value: `Nandivaram-Guduvancheri`, label: `Nandivaram-Guduvancheri` },
//   { value: `Nandura`, label: `Nandura` },
//   { value: `Nandurbar`, label: `Nandurbar` },
//   { value: `Nandyal`, label: `Nandyal` },
//   { value: `Nangal`, label: `Nangal` },
//   { value: `Nanjangud`, label: `Nanjangud` },
//   { value: `Nanjikottai`, label: `Nanjikottai` },
//   { value: `Nanpara`, label: `Nanpara` },
//   { value: `Narasapuram`, label: `Narasapuram` },
//   { value: `Narasaraopet`, label: `Narasaraopet` },
//   { value: `Naraura`, label: `Naraura` },
//   { value: `Narayanpet`, label: `Narayanpet` },
//   { value: `Narayanpur`, label: `Narayanpur` },
//   { value: `Nargund`, label: `Nargund` },
//   { value: `Narkatiaganj`, label: `Narkatiaganj` },
//   { value: `Narkhed`, label: `Narkhed` },
//   { value: `Narmada`, label: `Narmada` },
//   { value: `Narnaul`, label: `Narnaul` },
//   { value: `Narsinghgarh`, label: `Narsinghgarh` },
//   { value: `Narsinghpur`, label: `Narsinghpur` },
//   { value: `Narsipatnam`, label: `Narsipatnam` },
//   { value: `Narwana`, label: `Narwana` },
//   { value: `Nashik`, label: `Nashik` },
//   { value: `Nasirabad`, label: `Nasirabad` },
//   { value: `Natham`, label: `Natham` },
//   { value: `Nathdwara`, label: `Nathdwara` },
//   { value: `Naugachhia`, label: `Naugachhia` },
//   { value: `Naugawan Sadat`, label: `Naugawan Sadat` },
//   { value: `Nautanwa`, label: `Nautanwa` },
//   { value: `Navalgund`, label: `Navalgund` },
//   { value: `Navsari`, label: `Navsari` },
//   { value: `Nawabganj`, label: `Nawabganj` },
//   { value: `Nawada`, label: `Nawada` },
//   { value: `Nawanshahr`, label: `Nawanshahr` },
//   { value: `Nawapur`, label: `Nawapur` },
//   { value: `Nayagarh`, label: `Nayagarh` },
//   { value: `Nedumangad`, label: `Nedumangad` },
//   { value: `Neem-Ka-Thana`, label: `Neem-Ka-Thana` },
//   { value: `Neemuch`, label: `Neemuch` },
//   { value: `Nehtaur`, label: `Nehtaur` },
//   { value: `Nelamangala`, label: `Nelamangala` },
//   { value: `Nellikuppam`, label: `Nellikuppam` },
//   { value: `Nellore`, label: `Nellore` },
//   { value: `Nepanagar`, label: `Nepanagar` },
//   { value: `New Delhi`, label: `New Delhi` },
//   { value: `Neyveli (TS)`, label: `Neyveli (TS)` },
//   { value: `Neyyattinkara`, label: `Neyyattinkara` },
//   { value: `Nidadavole`, label: `Nidadavole` },
//   { value: `Nilambur`, label: `Nilambur` },
//   { value: `Nilanga`, label: `Nilanga` },
//   { value: `Nilgiris`, label: `Nilgiris` },
//   { value: `Nimbahera`, label: `Nimbahera` },
//   { value: `Nirmal`, label: `Nirmal` },
//   { value: `Niwai`, label: `Niwai` },
//   { value: `Niwari`, label: `Niwari` },
//   { value: `Nizamabad`, label: `Nizamabad` },
//   { value: `Nohar`, label: `Nohar` },
//   { value: `Noida`, label: `Noida` },
//   { value: `Nokha`, label: `Nokha` },
//   { value: `Nongstoin`, label: `Nongstoin` },
//   { value: `Noorpur`, label: `Noorpur` },
//   { value: `North 24 Parganas`, label: `North 24 Parganas` },
//   { value: `North Delhi`, label: `North Delhi` },
//   { value: `North East Delhi`, label: `North East Delhi` },
//   { value: `North Goa`, label: `North Goa` },
//   { value: `North Lakhimpur`, label: `North Lakhimpur` },
//   { value: `North Sikkim`, label: `North Sikkim` },
//   { value: `North Tripura`, label: `North Tripura` },
//   { value: `North West Delhi`, label: `North West Delhi` },
//   { value: `Nowgong`, label: `Nowgong` },
//   { value: `Nowrozabad (Khodargama)`, label: `Nowrozabad (Khodargama)` },
//   { value: `Nuapada`, label: `Nuapada` },
//   { value: `Nuzvid`, label: `Nuzvid` },
//   { value: `O' Valley`, label: `O' Valley` },
//   { value: `Obra`, label: `Obra` },
//   { value: `Oddanchatram`, label: `Oddanchatram` },
//   { value: `Ongole`, label: `Ongole` },
//   { value: `Orai`, label: `Orai` },
//   { value: `Osmanabad`, label: `Osmanabad` },
//   { value: `Other`, label: `Other` },
//   { value: `Ottappalam`, label: `Ottappalam` },
//   { value: `Ozar`, label: `Ozar` },
//   { value: `P.N.Patti`, label: `P.N.Patti` },
//   { value: `Pachora`, label: `Pachora` },
//   { value: `Pachore`, label: `Pachore` },
//   { value: `Pacode`, label: `Pacode` },
//   { value: `Padmanabhapuram`, label: `Padmanabhapuram` },
//   { value: `Padra`, label: `Padra` },
//   { value: `Padrauna`, label: `Padrauna` },
//   { value: `Paithan`, label: `Paithan` },
//   { value: `Pakaur`, label: `Pakaur` },
//   { value: `Pakur`, label: `Pakur` },
//   { value: `Palacole`, label: `Palacole` },
//   { value: `Palai`, label: `Palai` },
//   { value: `Palakkad`, label: `Palakkad` },
//   { value: `Palampur`, label: `Palampur` },
//   { value: `Palamu`, label: `Palamu` },
//   { value: `Palani`, label: `Palani` },
//   { value: `Palanpur`, label: `Palanpur` },
//   { value: `Palasa Kasibugga`, label: `Palasa Kasibugga` },
//   { value: `Palghar`, label: `Palghar` },
//   { value: `Pali`, label: `Pali` },
//   { value: `Palia Kalan`, label: `Palia Kalan` },
//   { value: `Palitana`, label: `Palitana` },
//   { value: `Palladam`, label: `Palladam` },
//   { value: `Pallapatti`, label: `Pallapatti` },
//   { value: `Pallikonda`, label: `Pallikonda` },
//   { value: `Palwal`, label: `Palwal` },
//   { value: `Palwancha`, label: `Palwancha` },
//   { value: `Panagar`, label: `Panagar` },
//   { value: `Panagudi`, label: `Panagudi` },
//   { value: `Panaji`, label: `Panaji` },
//   { value: `Panamattom`, label: `Panamattom` },
//   { value: `Panchkula`, label: `Panchkula` },
//   { value: `Panchla`, label: `Panchla` },
//   { value: `Panchmahal`, label: `Panchmahal` },
//   {
//     value: `Panchsheel Nagar district (Hapur)`,
//     label: `Panchsheel Nagar district (Hapur)`,
//   },
//   { value: `PandUrban Agglomeration`, label: `PandUrban Agglomeration` },
//   { value: `Pandharkaoda`, label: `Pandharkaoda` },
//   { value: `Pandharpur`, label: `Pandharpur` },
//   { value: `Pandhurna`, label: `Pandhurna` },
//   { value: `Panipat`, label: `Panipat` },
//   { value: `Panna`, label: `Panna` },
//   { value: `Panniyannur`, label: `Panniyannur` },
//   { value: `Panruti`, label: `Panruti` },
//   { value: `Panvel`, label: `Panvel` },
//   { value: `Pappinisseri`, label: `Pappinisseri` },
//   { value: `Papum Pare`, label: `Papum Pare` },
//   { value: `Paradip`, label: `Paradip` },
//   { value: `Paramakudi`, label: `Paramakudi` },
//   { value: `Parangipettai`, label: `Parangipettai` },
//   { value: `Parasi`, label: `Parasi` },
//   { value: `Paravoor`, label: `Paravoor` },
//   { value: `Parbhani`, label: `Parbhani` },
//   { value: `Pardi`, label: `Pardi` },
//   { value: `Parlakhemundi`, label: `Parlakhemundi` },
//   { value: `Parli`, label: `Parli` },
//   { value: `Partur`, label: `Partur` },
//   { value: `Parvathipuram`, label: `Parvathipuram` },
//   { value: `Pasan`, label: `Pasan` },
//   { value: `Paschim Medinipur`, label: `Paschim Medinipur` },
//   { value: `Paschim Punropara`, label: `Paschim Punropara` },
//   { value: `Pasighat`, label: `Pasighat` },
//   { value: `Patan`, label: `Patan` },
//   { value: `Pathanamthitta`, label: `Pathanamthitta` },
//   { value: `Pathankot`, label: `Pathankot` },
//   { value: `Pathardi`, label: `Pathardi` },
//   { value: `Pathri`, label: `Pathri` },
//   { value: `Patiala`, label: `Patiala` },
//   { value: `Patna`, label: `Patna` },
//   { value: `Patratu`, label: `Patratu` },
//   { value: `Pattamundai`, label: `Pattamundai` },
//   { value: `Patti`, label: `Patti` },
//   { value: `Pattran`, label: `Pattran` },
//   { value: `Pattukkottai`, label: `Pattukkottai` },
//   { value: `Patur`, label: `Patur` },
//   { value: `Pauni`, label: `Pauni` },
//   { value: `Pauri`, label: `Pauri` },
//   { value: `Pauri Garhwal`, label: `Pauri Garhwal` },
//   { value: `Pavagada`, label: `Pavagada` },
//   { value: `Pedana`, label: `Pedana` },
//   { value: `Peddapuram`, label: `Peddapuram` },
//   { value: `Pehowa`, label: `Pehowa` },
//   { value: `Pen`, label: `Pen` },
//   { value: `Perambalur`, label: `Perambalur` },
//   { value: `Peravurani`, label: `Peravurani` },
//   { value: `Peringathur`, label: `Peringathur` },
//   { value: `Perinthalmanna`, label: `Perinthalmanna` },
//   { value: `Periyakulam`, label: `Periyakulam` },
//   { value: `Periyasemur`, label: `Periyasemur` },
//   { value: `Pernampattu`, label: `Pernampattu` },
//   { value: `Perumbavoor`, label: `Perumbavoor` },
//   { value: `Petlad`, label: `Petlad` },
//   { value: `Phagwara`, label: `Phagwara` },
//   { value: `Phalodi`, label: `Phalodi` },
//   { value: `Phaltan`, label: `Phaltan` },
//   { value: `Phek`, label: `Phek` },
//   { value: `Phillaur`, label: `Phillaur` },
//   { value: `Phulabani`, label: `Phulabani` },
//   { value: `Phulera`, label: `Phulera` },
//   { value: `Phulpur`, label: `Phulpur` },
//   { value: `Phusro`, label: `Phusro` },
//   { value: `Pihani`, label: `Pihani` },
//   { value: `Pilani`, label: `Pilani` },
//   { value: `Pilibanga`, label: `Pilibanga` },
//   { value: `Pilibhit`, label: `Pilibhit` },
//   { value: `Pilkhuwa`, label: `Pilkhuwa` },
//   { value: `Pindwara`, label: `Pindwara` },
//   { value: `Pinjore`, label: `Pinjore` },
//   { value: `Pipar City`, label: `Pipar City` },
//   { value: `Pipariya`, label: `Pipariya` },
//   { value: `Piriyapatna`, label: `Piriyapatna` },
//   { value: `Piro`, label: `Piro` },
//   { value: `Pithampur`, label: `Pithampur` },
//   { value: `Pithapuram`, label: `Pithapuram` },
//   { value: `Pithoragarh`, label: `Pithoragarh` },
//   { value: `Pollachi`, label: `Pollachi` },
//   { value: `Polur`, label: `Polur` },
//   { value: `Pondicherry`, label: `Pondicherry` },
//   { value: `Ponnani`, label: `Ponnani` },
//   { value: `Ponneri`, label: `Ponneri` },
//   { value: `Ponnur`, label: `Ponnur` },
//   { value: `Poonch`, label: `Poonch` },
//   { value: `Porbandar`, label: `Porbandar` },
//   { value: `Porsa`, label: `Porsa` },
//   { value: `Port Blair`, label: `Port Blair` },
//   { value: `Powayan`, label: `Powayan` },
//   { value: `Prantij`, label: `Prantij` },
//   { value: `Pratapgarh`, label: `Pratapgarh` },
//   { value: `Prithvipur`, label: `Prithvipur` },
//   { value: `Proddatur`, label: `Proddatur` },
//   { value: `Pudukkottai`, label: `Pudukkottai` },
//   { value: `Pudupattinam`, label: `Pudupattinam` },
//   { value: `Pukhrayan`, label: `Pukhrayan` },
//   { value: `Pulgaon`, label: `Pulgaon` },
//   { value: `Puliyankudi`, label: `Puliyankudi` },
//   { value: `Pulwama`, label: `Pulwama` },
//   { value: `Punalur`, label: `Punalur` },
//   { value: `Punch`, label: `Punch` },
//   { value: `Pune`, label: `Pune` },
//   { value: `Punganur`, label: `Punganur` },
//   { value: `Punjaipugalur`, label: `Punjaipugalur` },
//   { value: `Puranpur`, label: `Puranpur` },
//   { value: `Purba Medinipur`, label: `Purba Medinipur` },
//   { value: `Puri`, label: `Puri` },
//   { value: `Purna`, label: `Purna` },
//   { value: `Purnia`, label: `Purnia` },
//   { value: `PurqUrban Agglomerationzi`, label: `PurqUrban Agglomerationzi` },
//   { value: `Purulia`, label: `Purulia` },
//   { value: `Purwa`, label: `Purwa` },
//   { value: `Pusad`, label: `Pusad` },
//   { value: `Puthuppally`, label: `Puthuppally` },
//   { value: `Puttur`, label: `Puttur` },
//   { value: `Qadian`, label: `Qadian` },
//   { value: `Raayachuru`, label: `Raayachuru` },
//   { value: `Rabkavi Banhatti`, label: `Rabkavi Banhatti` },
//   { value: `Radhanpur`, label: `Radhanpur` },
//   { value: `Rae Bareli`, label: `Rae Bareli` },
//   { value: `Raebareli`, label: `Raebareli` },
//   { value: `Rafiganj`, label: `Rafiganj` },
//   { value: `Raghogarh-Vijaypur`, label: `Raghogarh-Vijaypur` },
//   { value: `Raghunathganj`, label: `Raghunathganj` },
//   { value: `Raghunathpur`, label: `Raghunathpur` },
//   { value: `Rahatgarh`, label: `Rahatgarh` },
//   { value: `Rahuri`, label: `Rahuri` },
//   { value: `Raichur`, label: `Raichur` },
//   { value: `Raigad`, label: `Raigad` },
//   { value: `Raiganj`, label: `Raiganj` },
//   { value: `Raigarh`, label: `Raigarh` },
//   { value: `Raikot`, label: `Raikot` },
//   { value: `Raipur`, label: `Raipur` },
//   { value: `Rairangpur`, label: `Rairangpur` },
//   { value: `Raisen`, label: `Raisen` },
//   { value: `Raisinghnagar`, label: `Raisinghnagar` },
//   { value: `Rajagangapur`, label: `Rajagangapur` },
//   { value: `Rajahmundry`, label: `Rajahmundry` },
//   { value: `Rajakhera`, label: `Rajakhera` },
//   { value: `Rajaldesar`, label: `Rajaldesar` },
//   { value: `Rajam`, label: `Rajam` },
//   { value: `Rajampet`, label: `Rajampet` },
//   { value: `Rajapalayam`, label: `Rajapalayam` },
//   { value: `Rajauri`, label: `Rajauri` },
//   { value: `Rajgarh`, label: `Rajgarh` },
//   { value: `Rajgarh (Alwar)`, label: `Rajgarh (Alwar)` },
//   { value: `Rajgarh (Churu)`, label: `Rajgarh (Churu)` },
//   { value: `Rajgir`, label: `Rajgir` },
//   { value: `Rajkot`, label: `Rajkot` },
//   { value: `Rajnandgaon`, label: `Rajnandgaon` },
//   { value: `Rajpipla`, label: `Rajpipla` },
//   { value: `Rajpura`, label: `Rajpura` },
//   { value: `Rajsamand`, label: `Rajsamand` },
//   { value: `Rajula`, label: `Rajula` },
//   { value: `Rajura`, label: `Rajura` },
//   {
//     value: `Ramabai Nagar (Kanpur Dehat)`,
//     label: `Ramabai Nagar (Kanpur Dehat)`,
//   },
//   { value: `Ramachandrapuram`, label: `Ramachandrapuram` },
//   { value: `Ramagundam`, label: `Ramagundam` },
//   { value: `Ramanagara`, label: `Ramanagara` },
//   { value: `Ramanagaram`, label: `Ramanagaram` },
//   { value: `Ramanathapuram`, label: `Ramanathapuram` },
//   { value: `Ramban`, label: `Ramban` },
//   { value: `Ramdurg`, label: `Ramdurg` },
//   { value: `Rameshwaram`, label: `Rameshwaram` },
//   { value: `Ramganj Mandi`, label: `Ramganj Mandi` },
//   { value: `Ramgarh`, label: `Ramgarh` },
//   { value: `Ramnagar`, label: `Ramnagar` },
//   { value: `Ramngarh`, label: `Ramngarh` },
//   { value: `Rampur`, label: `Rampur` },
//   { value: `Rampur Maniharan`, label: `Rampur Maniharan` },
//   { value: `Rampura Phul`, label: `Rampura Phul` },
//   { value: `Rampurhat`, label: `Rampurhat` },
//   { value: `Ramtek`, label: `Ramtek` },
//   { value: `Ranaghat`, label: `Ranaghat` },
//   { value: `Ranavav`, label: `Ranavav` },
//   { value: `Ranchi`, label: `Ranchi` },
//   { value: `Ranebennuru`, label: `Ranebennuru` },
//   { value: `Rangia`, label: `Rangia` },
//   { value: `Rania`, label: `Rania` },
//   { value: `Ranibennur`, label: `Ranibennur` },
//   { value: `Ranipet`, label: `Ranipet` },
//   { value: `Rapar`, label: `Rapar` },
//   { value: `Rasipuram`, label: `Rasipuram` },
//   { value: `Rasra`, label: `Rasra` },
//   { value: `Ratangarh`, label: `Ratangarh` },
//   { value: `Rath`, label: `Rath` },
//   { value: `Ratia`, label: `Ratia` },
//   { value: `Ratlam`, label: `Ratlam` },
//   { value: `Ratnagiri`, label: `Ratnagiri` },
//   { value: `Rau`, label: `Rau` },
//   { value: `Raurkela`, label: `Raurkela` },
//   { value: `Raver`, label: `Raver` },
//   { value: `Rawatbhata`, label: `Rawatbhata` },
//   { value: `Rawatsar`, label: `Rawatsar` },
//   { value: `Raxaul Bazar`, label: `Raxaul Bazar` },
//   { value: `Rayachoti`, label: `Rayachoti` },
//   { value: `Rayadurg`, label: `Rayadurg` },
//   { value: `Rayagada`, label: `Rayagada` },
//   { value: `Reasi`, label: `Reasi` },
//   { value: `Reengus`, label: `Reengus` },
//   { value: `Rehli`, label: `Rehli` },
//   { value: `Renigunta`, label: `Renigunta` },
//   { value: `Renukoot`, label: `Renukoot` },
//   { value: `Reoti`, label: `Reoti` },
//   { value: `Repalle`, label: `Repalle` },
//   { value: `Revelganj`, label: `Revelganj` },
//   { value: `Rewa`, label: `Rewa` },
//   { value: `Rewari`, label: `Rewari` },
//   { value: `Ri Bhoi`, label: `Ri Bhoi` },
//   { value: `Rishikesh`, label: `Rishikesh` },
//   { value: `Risod`, label: `Risod` },
//   { value: `Robertsganj`, label: `Robertsganj` },
//   { value: `Robertson Pet`, label: `Robertson Pet` },
//   { value: `Rohtak`, label: `Rohtak` },
//   { value: `Rohtas`, label: `Rohtas` },
//   { value: `Ron`, label: `Ron` },
//   { value: `Roorkee`, label: `Roorkee` },
//   { value: `Rosera`, label: `Rosera` },
//   { value: `Rudauli`, label: `Rudauli` },
//   { value: `Rudraprayag`, label: `Rudraprayag` },
//   { value: `Rudrapur`, label: `Rudrapur` },
//   { value: `Rupnagar`, label: `Rupnagar` },
//   { value: `SUrban Agglomerationr`, label: `SUrban Agglomerationr` },
//   { value: `Sabalgarh`, label: `Sabalgarh` },
//   { value: `Sabarkantha`, label: `Sabarkantha` },
//   { value: `Sadabad`, label: `Sadabad` },
//   { value: `Sadalagi`, label: `Sadalagi` },
//   { value: `Sadasivpet`, label: `Sadasivpet` },
//   { value: `Sadri`, label: `Sadri` },
//   { value: `Sadulpur`, label: `Sadulpur` },
//   { value: `Sadulshahar`, label: `Sadulshahar` },
//   { value: `Safidon`, label: `Safidon` },
//   { value: `Safipur`, label: `Safipur` },
//   { value: `Sagar`, label: `Sagar` },
//   { value: `Sagara`, label: `Sagara` },
//   { value: `Sagwara`, label: `Sagwara` },
//   { value: `Saharanpur`, label: `Saharanpur` },
//   { value: `Saharsa`, label: `Saharsa` },
//   { value: `Sahaspur`, label: `Sahaspur` },
//   { value: `Sahaswan`, label: `Sahaswan` },
//   { value: `Sahawar`, label: `Sahawar` },
//   { value: `Sahibganj`, label: `Sahibganj` },
//   { value: `Sahjanwa`, label: `Sahjanwa` },
//   { value: `Saidpur`, label: `Saidpur` },
//   { value: `Saiha`, label: `Saiha` },
//   { value: `Sailu`, label: `Sailu` },
//   { value: `Sainthia`, label: `Sainthia` },
//   { value: `Sakaleshapura`, label: `Sakaleshapura` },
//   { value: `Sakti`, label: `Sakti` },
//   { value: `Salaya`, label: `Salaya` },
//   { value: `Salem`, label: `Salem` },
//   { value: `Salur`, label: `Salur` },
//   { value: `Samalkha`, label: `Samalkha` },
//   { value: `Samalkot`, label: `Samalkot` },
//   { value: `Samana`, label: `Samana` },
//   { value: `Samastipur`, label: `Samastipur` },
//   { value: `Samba`, label: `Samba` },
//   { value: `Sambalpur`, label: `Sambalpur` },
//   { value: `Sambhal`, label: `Sambhal` },
//   { value: `Sambhar`, label: `Sambhar` },
//   { value: `Samdhan`, label: `Samdhan` },
//   { value: `Samthar`, label: `Samthar` },
//   { value: `Sanand`, label: `Sanand` },
//   { value: `Sanawad`, label: `Sanawad` },
//   { value: `Sanchore`, label: `Sanchore` },
//   { value: `Sandi`, label: `Sandi` },
//   { value: `Sandila`, label: `Sandila` },
//   { value: `Sanduru`, label: `Sanduru` },
//   { value: `Sangamner`, label: `Sangamner` },
//   { value: `Sangareddy`, label: `Sangareddy` },
//   { value: `Sangaria`, label: `Sangaria` },
//   { value: `Sangli`, label: `Sangli` },
//   { value: `Sangole`, label: `Sangole` },
//   { value: `Sangrur`, label: `Sangrur` },
//   { value: `Sankarankovil`, label: `Sankarankovil` },
//   { value: `Sankari`, label: `Sankari` },
//   { value: `Sankeshwara`, label: `Sankeshwara` },
//   { value: `Sant Kabir Nagar`, label: `Sant Kabir Nagar` },
//   { value: `Sant Ravidas Nagar`, label: `Sant Ravidas Nagar` },
//   { value: `Santipur`, label: `Santipur` },
//   { value: `Saran`, label: `Saran` },
//   { value: `Sarangpur`, label: `Sarangpur` },
//   { value: `Sardarshahar`, label: `Sardarshahar` },
//   { value: `Sardhana`, label: `Sardhana` },
//   { value: `Sarni`, label: `Sarni` },
//   { value: `Sarsod`, label: `Sarsod` },
//   { value: `Sasaram`, label: `Sasaram` },
//   { value: `Sasvad`, label: `Sasvad` },
//   { value: `Satana`, label: `Satana` },
//   { value: `Satara`, label: `Satara` },
//   { value: `Sathyamangalam`, label: `Sathyamangalam` },
//   { value: `Satna`, label: `Satna` },
//   { value: `Sattenapalle`, label: `Sattenapalle` },
//   { value: `Sattur`, label: `Sattur` },
//   { value: `Saunda`, label: `Saunda` },
//   { value: `Saundatti-Yellamma`, label: `Saundatti-Yellamma` },
//   { value: `Sausar`, label: `Sausar` },
//   { value: `Savanur`, label: `Savanur` },
//   { value: `Savarkundla`, label: `Savarkundla` },
//   { value: `Savner`, label: `Savner` },
//   { value: `Sawai Madhopur`, label: `Sawai Madhopur` },
//   { value: `Sawantwadi`, label: `Sawantwadi` },
//   { value: `Sedam`, label: `Sedam` },
//   { value: `Sehore`, label: `Sehore` },
//   { value: `Senapati`, label: `Senapati` },
//   { value: `Sendhwa`, label: `Sendhwa` },
//   { value: `Seohara`, label: `Seohara` },
//   { value: `Seoni`, label: `Seoni` },
//   { value: `Seoni-Malwa`, label: `Seoni-Malwa` },
//   { value: `Seraikela Kharsawan`, label: `Seraikela Kharsawan` },
//   { value: `Serchhip`, label: `Serchhip` },
//   { value: `Shahabad`, label: `Shahabad` },
//   { value: `Shahabad, Hardoi`, label: `Shahabad, Hardoi` },
//   { value: `Shahabad, Rampur`, label: `Shahabad, Rampur` },
//   { value: `Shahade`, label: `Shahade` },
//   { value: `Shahbad`, label: `Shahbad` },
//   { value: `Shahdol`, label: `Shahdol` },
//   { value: `Shahganj`, label: `Shahganj` },
//   { value: `Shahjahanpur`, label: `Shahjahanpur` },
//   { value: `Shahpur`, label: `Shahpur` },
//   { value: `Shahpura`, label: `Shahpura` },
//   { value: `Shajapur`, label: `Shajapur` },
//   { value: `Shamgarh`, label: `Shamgarh` },
//   { value: `Shamli`, label: `Shamli` },
//   { value: `Shamsabad, Agra`, label: `Shamsabad, Agra` },
//   { value: `Shamsabad, Farrukhabad`, label: `Shamsabad, Farrukhabad` },
//   { value: `Shegaon`, label: `Shegaon` },
//   { value: `Sheikhpura`, label: `Sheikhpura` },
//   { value: `Shendurjana`, label: `Shendurjana` },
//   { value: `Shenkottai`, label: `Shenkottai` },
//   { value: `Sheoganj`, label: `Sheoganj` },
//   { value: `Sheohar`, label: `Sheohar` },
//   { value: `Sheopur`, label: `Sheopur` },
//   { value: `Sherghati`, label: `Sherghati` },
//   { value: `Sherkot`, label: `Sherkot` },
//   { value: `Shiggaon`, label: `Shiggaon` },
//   { value: `Shikaripur`, label: `Shikaripur` },
//   { value: `Shikarpur, Bulandshahr`, label: `Shikarpur, Bulandshahr` },
//   { value: `Shikohabad`, label: `Shikohabad` },
//   { value: `Shillong`, label: `Shillong` },
//   { value: `Shimla`, label: `Shimla` },
//   { value: `Shimoga`, label: `Shimoga` },
//   { value: `Shirdi`, label: `Shirdi` },
//   { value: `Shirpur-Warwade`, label: `Shirpur-Warwade` },
//   { value: `Shirur`, label: `Shirur` },
//   { value: `Shishgarh`, label: `Shishgarh` },
//   { value: `Shivamogga`, label: `Shivamogga` },
//   { value: `Shivpuri`, label: `Shivpuri` },
//   { value: `Sholavandan`, label: `Sholavandan` },
//   { value: `Sholingur`, label: `Sholingur` },
//   { value: `Shopian`, label: `Shopian` },
//   { value: `Shoranur`, label: `Shoranur` },
//   { value: `Shravasti`, label: `Shravasti` },
//   { value: `Shrigonda`, label: `Shrigonda` },
//   { value: `Shrirampur`, label: `Shrirampur` },
//   { value: `Shrirangapattana`, label: `Shrirangapattana` },
//   { value: `Shujalpur`, label: `Shujalpur` },
//   { value: `Siana`, label: `Siana` },
//   { value: `Sibsagar`, label: `Sibsagar` },
//   { value: `Siddharthnagar`, label: `Siddharthnagar` },
//   { value: `Siddipet`, label: `Siddipet` },
//   { value: `Sidhi`, label: `Sidhi` },
//   { value: `Sidhpur`, label: `Sidhpur` },
//   { value: `Sidlaghatta`, label: `Sidlaghatta` },
//   { value: `Sihor`, label: `Sihor` },
//   { value: `Sihora`, label: `Sihora` },
//   { value: `Sikanderpur`, label: `Sikanderpur` },
//   { value: `Sikandra Rao`, label: `Sikandra Rao` },
//   { value: `Sikandrabad`, label: `Sikandrabad` },
//   { value: `Sikar`, label: `Sikar` },
//   { value: `Silao`, label: `Silao` },
//   { value: `Silapathar`, label: `Silapathar` },
//   { value: `Silchar`, label: `Silchar` },
//   { value: `Siliguri`, label: `Siliguri` },
//   { value: `Sillod`, label: `Sillod` },
//   { value: `Silvassa`, label: `Silvassa` },
//   { value: `Simdega`, label: `Simdega` },
//   { value: `Sindagi`, label: `Sindagi` },
//   { value: `Sindhagi`, label: `Sindhagi` },
//   { value: `Sindhnur`, label: `Sindhnur` },
//   { value: `Sindhudurg`, label: `Sindhudurg` },
//   { value: `Singrauli`, label: `Singrauli` },
//   { value: `Sinnar`, label: `Sinnar` },
//   { value: `Sira`, label: `Sira` },
//   { value: `Sircilla`, label: `Sircilla` },
//   { value: `Sirhind Fatehgarh Sahib`, label: `Sirhind Fatehgarh Sahib` },
//   { value: `Sirkali`, label: `Sirkali` },
//   { value: `Sirmaur`, label: `Sirmaur` },
//   { value: `Sirohi`, label: `Sirohi` },
//   { value: `Sironj`, label: `Sironj` },
//   { value: `Sirsa`, label: `Sirsa` },
//   { value: `Sirsaganj`, label: `Sirsaganj` },
//   { value: `Sirsi`, label: `Sirsi` },
//   { value: `Siruguppa`, label: `Siruguppa` },
//   { value: `Sitamarhi`, label: `Sitamarhi` },
//   { value: `Sitapur`, label: `Sitapur` },
//   { value: `Sitarganj`, label: `Sitarganj` },
//   { value: `Sivaganga`, label: `Sivaganga` },
//   { value: `Sivagiri`, label: `Sivagiri` },
//   { value: `Sivakasi`, label: `Sivakasi` },
//   { value: `Siwan`, label: `Siwan` },
//   { value: `Sohagpur`, label: `Sohagpur` },
//   { value: `Sohna`, label: `Sohna` },
//   { value: `Sojat`, label: `Sojat` },
//   { value: `Solan`, label: `Solan` },
//   { value: `Solapur`, label: `Solapur` },
//   { value: `Sonamukhi`, label: `Sonamukhi` },
//   { value: `Sonbhadra`, label: `Sonbhadra` },
//   { value: `Sonepur`, label: `Sonepur` },
//   { value: `Songadh`, label: `Songadh` },
//   { value: `Sonipat`, label: `Sonipat` },
//   { value: `Sonitpur`, label: `Sonitpur` },
//   { value: `Sopore`, label: `Sopore` },
//   { value: `Soro`, label: `Soro` },
//   { value: `Soron`, label: `Soron` },
//   { value: `South 24 Parganas`, label: `South 24 Parganas` },
//   { value: `South Delhi`, label: `South Delhi` },
//   { value: `South Garo Hills`, label: `South Garo Hills` },
//   { value: `South Goa`, label: `South Goa` },
//   { value: `South Sikkim`, label: `South Sikkim` },
//   { value: `South Tripura`, label: `South Tripura` },
//   { value: `South West Delhi`, label: `South West Delhi` },
//   { value: `Soyagaon`, label: `Soyagaon` },
//   { value: `Sri Madhopur`, label: `Sri Madhopur` },
//   { value: `Sri Muktsar Sahib`, label: `Sri Muktsar Sahib` },
//   { value: `Srikakulam`, label: `Srikakulam` },
//   { value: `Srikalahasti`, label: `Srikalahasti` },
//   { value: `Srinagar`, label: `Srinagar` },
//   { value: `Srinivaspur`, label: `Srinivaspur` },
//   { value: `Srirampore`, label: `Srirampore` },
//   {
//     value: `Srisailam Project (Right Flank Colony) Township`,
//     label: `Srisailam Project (Right Flank Colony) Township`,
//   },
//   { value: `Srivilliputhur`, label: `Srivilliputhur` },
//   { value: `Subarnapur (Sonepur)`, label: `Subarnapur (Sonepur)` },
//   { value: `Sugauli`, label: `Sugauli` },
//   { value: `Sujangarh`, label: `Sujangarh` },
//   { value: `Sujanpur`, label: `Sujanpur` },
//   { value: `Sullurpeta`, label: `Sullurpeta` },
//   { value: `Sultanganj`, label: `Sultanganj` },
//   { value: `Sultanpur`, label: `Sultanpur` },
//   { value: `Sumerpur`, label: `Sumerpur` },
//   { value: `Sunabeda`, label: `Sunabeda` },
//   { value: `Sunam`, label: `Sunam` },
//   { value: `Sundargarh`, label: `Sundargarh` },
//   { value: `Sundarnagar`, label: `Sundarnagar` },
//   { value: `Sundergarh`, label: `Sundergarh` },
//   { value: `Supaul`, label: `Supaul` },
//   { value: `Surandai`, label: `Surandai` },
//   { value: `Surapura`, label: `Surapura` },
//   { value: `Surat`, label: `Surat` },
//   { value: `Suratgarh`, label: `Suratgarh` },
//   { value: `Surendranagar`, label: `Surendranagar` },
//   { value: `Surguja`, label: `Surguja` },
//   { value: `Suri`, label: `Suri` },
//   { value: `Suriyampalayam`, label: `Suriyampalayam` },
//   { value: `Suryapet`, label: `Suryapet` },
//   { value: `Tadepalligudem`, label: `Tadepalligudem` },
//   { value: `Tadpatri`, label: `Tadpatri` },
//   { value: `Takhatgarh`, label: `Takhatgarh` },
//   { value: `Taki`, label: `Taki` },
//   { value: `Talaja`, label: `Talaja` },
//   { value: `Talcher`, label: `Talcher` },
//   { value: `Talegaon Dabhade`, label: `Talegaon Dabhade` },
//   { value: `Talikota`, label: `Talikota` },
//   { value: `Taliparamba`, label: `Taliparamba` },
//   { value: `Talode`, label: `Talode` },
//   { value: `Talwara`, label: `Talwara` },
//   { value: `Tamenglong`, label: `Tamenglong` },
//   { value: `Tamluk`, label: `Tamluk` },
//   { value: `Tanda`, label: `Tanda` },
//   { value: `Tandur`, label: `Tandur` },
//   { value: `Tanuku`, label: `Tanuku` },
//   { value: `Tarakeswar`, label: `Tarakeswar` },
//   { value: `Tarana`, label: `Tarana` },
//   { value: `Taranagar`, label: `Taranagar` },
//   { value: `Taraori`, label: `Taraori` },
//   { value: `Tarbha`, label: `Tarbha` },
//   { value: `Tarikere`, label: `Tarikere` },
//   { value: `Tarn Taran`, label: `Tarn Taran` },
//   { value: `Tasgaon`, label: `Tasgaon` },
//   { value: `Tawang`, label: `Tawang` },
//   { value: `Tehri`, label: `Tehri` },
//   { value: `Tehri Garhwal`, label: `Tehri Garhwal` },
//   { value: `Tekkalakote`, label: `Tekkalakote` },
//   { value: `Tenali`, label: `Tenali` },
//   { value: `Tenkasi`, label: `Tenkasi` },
//   { value: `Tenu dam-*****-Kathhara`, label: `Tenu dam-*****-Kathhara` },
//   { value: `Terdal`, label: `Terdal` },
//   { value: `Tezpur`, label: `Tezpur` },
//   { value: `Thakurdwara`, label: `Thakurdwara` },
//   { value: `Thammampatti`, label: `Thammampatti` },
//   { value: `Thana Bhawan`, label: `Thana Bhawan` },
//   { value: `Thane`, label: `Thane` },
//   { value: `Thanesar`, label: `Thanesar` },
//   { value: `Thangadh`, label: `Thangadh` },
//   { value: `Thanjavur`, label: `Thanjavur` },
//   { value: `Tharad`, label: `Tharad` },
//   { value: `Tharamangalam`, label: `Tharamangalam` },
//   { value: `Tharangambadi`, label: `Tharangambadi` },
//   { value: `The Dangs`, label: `The Dangs` },
//   { value: `Theni`, label: `Theni` },
//   { value: `Theni Allinagaram`, label: `Theni Allinagaram` },
//   { value: `Thirumangalam`, label: `Thirumangalam` },
//   { value: `Thirupuvanam`, label: `Thirupuvanam` },
//   { value: `Thiruthuraipoondi`, label: `Thiruthuraipoondi` },
//   { value: `Thiruvalla`, label: `Thiruvalla` },
//   { value: `Thiruvallur`, label: `Thiruvallur` },
//   { value: `Thiruvananthapuram`, label: `Thiruvananthapuram` },
//   { value: `Thiruvarur`, label: `Thiruvarur` },
//   { value: `Thodupuzha`, label: `Thodupuzha` },
//   { value: `Thoothukudi`, label: `Thoothukudi` },
//   { value: `Thoubal`, label: `Thoubal` },
//   { value: `Thrissur`, label: `Thrissur` },
//   { value: `Thuraiyur`, label: `Thuraiyur` },
//   { value: `Tikamgarh`, label: `Tikamgarh` },
//   { value: `Tilda Newra`, label: `Tilda Newra` },
//   { value: `Tilhar`, label: `Tilhar` },
//   { value: `Tindivanam`, label: `Tindivanam` },
//   { value: `Tinsukia`, label: `Tinsukia` },
//   { value: `Tiptur`, label: `Tiptur` },
//   { value: `Tirap`, label: `Tirap` },
//   { value: `Tirora`, label: `Tirora` },
//   { value: `Tiruchendur`, label: `Tiruchendur` },
//   { value: `Tiruchengode`, label: `Tiruchengode` },
//   { value: `Tiruchirappalli`, label: `Tiruchirappalli` },
//   { value: `Tirukalukundram`, label: `Tirukalukundram` },
//   { value: `Tirukkoyilur`, label: `Tirukkoyilur` },
//   { value: `Tirunelveli`, label: `Tirunelveli` },
//   { value: `Tirupathur`, label: `Tirupathur` },
//   { value: `Tirupati`, label: `Tirupati` },
//   { value: `Tiruppur`, label: `Tiruppur` },
//   { value: `Tirupur`, label: `Tirupur` },
//   { value: `Tirur`, label: `Tirur` },
//   { value: `Tiruttani`, label: `Tiruttani` },
//   { value: `Tiruvallur`, label: `Tiruvallur` },
//   { value: `Tiruvannamalai`, label: `Tiruvannamalai` },
//   { value: `Tiruvarur`, label: `Tiruvarur` },
//   { value: `Tiruvethipuram`, label: `Tiruvethipuram` },
//   { value: `Tiruvuru`, label: `Tiruvuru` },
//   { value: `Tirwaganj`, label: `Tirwaganj` },
//   { value: `Titlagarh`, label: `Titlagarh` },
//   { value: `Tittakudi`, label: `Tittakudi` },
//   { value: `Todabhim`, label: `Todabhim` },
//   { value: `Todaraisingh`, label: `Todaraisingh` },
//   { value: `Tohana`, label: `Tohana` },
//   { value: `Tonk`, label: `Tonk` },
//   { value: `Tuensang`, label: `Tuensang` },
//   { value: `Tuljapur`, label: `Tuljapur` },
//   { value: `Tulsipur`, label: `Tulsipur` },
//   { value: `Tumkur`, label: `Tumkur` },
//   { value: `Tumsar`, label: `Tumsar` },
//   { value: `Tundla`, label: `Tundla` },
//   { value: `Tuni`, label: `Tuni` },
//   { value: `Tura`, label: `Tura` },
//   { value: `Uchgaon`, label: `Uchgaon` },
//   { value: `Udaipur`, label: `Udaipur` },
//   { value: `Udaipurwati`, label: `Udaipurwati` },
//   { value: `Udalguri`, label: `Udalguri` },
//   { value: `Udgir`, label: `Udgir` },
//   { value: `Udhagamandalam`, label: `Udhagamandalam` },
//   { value: `Udham Singh Nagar`, label: `Udham Singh Nagar` },
//   { value: `Udhampur`, label: `Udhampur` },
//   { value: `Udumalaipettai`, label: `Udumalaipettai` },
//   { value: `Udupi`, label: `Udupi` },
//   { value: `Ujhani`, label: `Ujhani` },
//   { value: `Ujjain`, label: `Ujjain` },
//   { value: `Ukhrul`, label: `Ukhrul` },
//   { value: `Umarga`, label: `Umarga` },
//   { value: `Umaria`, label: `Umaria` },
//   { value: `Umarkhed`, label: `Umarkhed` },
//   { value: `Umbergaon`, label: `Umbergaon` },
//   { value: `Umred`, label: `Umred` },
//   { value: `Umreth`, label: `Umreth` },
//   { value: `Una`, label: `Una` },
//   { value: `Unjha`, label: `Unjha` },
//   { value: `Unnamalaikadai`, label: `Unnamalaikadai` },
//   { value: `Unnao`, label: `Unnao` },
//   { value: `Upleta`, label: `Upleta` },
//   { value: `Upper Siang`, label: `Upper Siang` },
//   { value: `Upper Subansiri`, label: `Upper Subansiri` },
//   { value: `Uran`, label: `Uran` },
//   { value: `Uran Islampur`, label: `Uran Islampur` },
//   { value: `Uravakonda`, label: `Uravakonda` },
//   { value: `Urmar Tanda`, label: `Urmar Tanda` },
//   { value: `Usilampatti`, label: `Usilampatti` },
//   { value: `Uthamapalayam`, label: `Uthamapalayam` },
//   { value: `Uthiramerur`, label: `Uthiramerur` },
//   { value: `Utraula`, label: `Utraula` },
//   { value: `Uttar Dinajpur`, label: `Uttar Dinajpur` },
//   { value: `Uttara Kannada`, label: `Uttara Kannada` },
//   { value: `Uttarkashi`, label: `Uttarkashi` },
//   { value: `Vadakkuvalliyur`, label: `Vadakkuvalliyur` },
//   { value: `Vadalur`, label: `Vadalur` },
//   { value: `Vadgaon Kasba`, label: `Vadgaon Kasba` },
//   { value: `Vadipatti`, label: `Vadipatti` },
//   { value: `Vadnagar`, label: `Vadnagar` },
//   { value: `Vadodara`, label: `Vadodara` },
//   { value: `Vaijapur`, label: `Vaijapur` },
//   { value: `Vaikom`, label: `Vaikom` },
//   { value: `Vaishali`, label: `Vaishali` },
//   { value: `Valparai`, label: `Valparai` },
//   { value: `Valsad`, label: `Valsad` },
//   { value: `Vandavasi`, label: `Vandavasi` },
//   { value: `Vaniyambadi`, label: `Vaniyambadi` },
//   { value: `Vapi`, label: `Vapi` },
//   { value: `Varanasi`, label: `Varanasi` },
//   { value: `Varkala`, label: `Varkala` },
//   { value: `Vasai-Virar`, label: `Vasai-Virar` },
//   { value: `Vatakara`, label: `Vatakara` },
//   { value: `Vedaranyam`, label: `Vedaranyam` },
//   { value: `Vellakoil`, label: `Vellakoil` },
//   { value: `Vellore`, label: `Vellore` },
//   { value: `Venkatagiri`, label: `Venkatagiri` },
//   { value: `Veraval`, label: `Veraval` },
//   { value: `Vidisha`, label: `Vidisha` },
//   { value: `Vijainagar, Ajmer`, label: `Vijainagar, Ajmer` },
//   { value: `Vijapur`, label: `Vijapur` },
//   { value: `Vijayapura`, label: `Vijayapura` },
//   { value: `Vijayawada`, label: `Vijayawada` },
//   { value: `Vijaypur`, label: `Vijaypur` },
//   { value: `Vikarabad`, label: `Vikarabad` },
//   { value: `Vikramasingapuram`, label: `Vikramasingapuram` },
//   { value: `Viluppuram`, label: `Viluppuram` },
//   { value: `Vinukonda`, label: `Vinukonda` },
//   { value: `Viramgam`, label: `Viramgam` },
//   { value: `Virudhachalam`, label: `Virudhachalam` },
//   { value: `Virudhunagar`, label: `Virudhunagar` },
//   { value: `Visakhapatnam`, label: `Visakhapatnam` },
//   { value: `Visnagar`, label: `Visnagar` },
//   { value: `Viswanatham`, label: `Viswanatham` },
//   { value: `Vita`, label: `Vita` },
//   { value: `Vizianagaram`, label: `Vizianagaram` },
//   { value: `Vrindavan`, label: `Vrindavan` },
//   { value: `Vyara`, label: `Vyara` },
//   { value: `Wadgaon Road`, label: `Wadgaon Road` },
//   { value: `Wadhwan`, label: `Wadhwan` },
//   { value: `Wadi`, label: `Wadi` },
//   { value: `Wai`, label: `Wai` },
//   { value: `Wanaparthy`, label: `Wanaparthy` },
//   { value: `Wani`, label: `Wani` },
//   { value: `Wankaner`, label: `Wankaner` },
//   { value: `Wara Seoni`, label: `Wara Seoni` },
//   { value: `Warangal`, label: `Warangal` },
//   { value: `Wardha`, label: `Wardha` },
//   { value: `Warhapur`, label: `Warhapur` },
//   { value: `Warisaliganj`, label: `Warisaliganj` },
//   { value: `Warora`, label: `Warora` },
//   { value: `Warud`, label: `Warud` },
//   { value: `Washim`, label: `Washim` },
//   { value: `Wayanad`, label: `Wayanad` },
//   { value: `West Champaran`, label: `West Champaran` },
//   { value: `West Delhi`, label: `West Delhi` },
//   { value: `West Garo Hills`, label: `West Garo Hills` },
//   { value: `West Kameng`, label: `West Kameng` },
//   { value: `West Khasi Hills`, label: `West Khasi Hills` },
//   { value: `West Siang`, label: `West Siang` },
//   { value: `West Sikkim`, label: `West Sikkim` },
//   { value: `West Singhbhum`, label: `West Singhbhum` },
//   { value: `West Tripura`, label: `West Tripura` },
//   { value: `Wokha`, label: `Wokha` },
//   { value: `Yadgir`, label: `Yadgir` },
//   { value: `Yamuna Nagar`, label: `Yamuna Nagar` },
//   { value: `Yamunanagar`, label: `Yamunanagar` },
//   { value: `Yanam`, label: `Yanam` },
//   { value: `Yavatmal`, label: `Yavatmal` },
//   { value: `Yawal`, label: `Yawal` },
//   { value: `Yellandu`, label: `Yellandu` },
//   { value: `Yemmiganur`, label: `Yemmiganur` },
//   { value: `Yerraguntla`, label: `Yerraguntla` },
//   { value: `Yevla`, label: `Yevla` },
//   { value: `Zaidpur`, label: `Zaidpur` },
//   { value: `Zamania`, label: `Zamania` },
//   { value: `Zira`, label: `Zira` },
//   { value: `Zirakpur`, label: `Zirakpur` },
//   { value: `Zunheboto`, label: `Zunheboto` },
// ];
